<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Exceptions;

use MagentoCommunityLib\APIException;
use MagentoCommunityLib\APIHelper;

/**
 * @todo Write general description for this model
 */
class ErrorResponseException extends APIException
{
    /**
     * Error message
     * @required
     * @var string $message public property
     */
    public $message;

    /**
     * Errors list
     * @var \MagentoCommunityLib\Models\ErrorErrorsItem[]|null $errors public property
     */
    public $errors;

    /**
     * Error code
     * @var integer|null $code public property
     */
    public $code;

    /**
     * Error parameters list
     * @var \MagentoCommunityLib\Models\ErrorParametersItem[]|null $parameters public property
     */
    public $parameters;

    /**
     * Stack trace
     * @var string|null $trace public property
     */
    public $trace;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct($reason, $context)
    {
        parent::__construct($reason, $context);
    }

    /**
     * Unbox response into this exception class
     */
    public function unbox()
    {
        APIHelper::deserialize(self::getResponseBody(), $this, false, false);
    }
}
