<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogSpecialPriceStorageV1GetPostBody implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var array $skus public property
     */
    public $skus;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $skus Initialization value for $this->skus
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->skus = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['skus'] = $this->skus;

        return $json;
    }
}
