<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Tier price interface.
 */
class CatalogDataTierPriceInterface implements JsonSerializable
{
    /**
     * Tier price.
     * @required
     * @var double $price public property
     */
    public $price;

    /**
     * Tier price type.
     * @required
     * @maps price_type
     * @var string $priceType public property
     */
    public $priceType;

    /**
     * Website id.
     * @required
     * @maps website_id
     * @var integer $websiteId public property
     */
    public $websiteId;

    /**
     * SKU.
     * @required
     * @var string $sku public property
     */
    public $sku;

    /**
     * Customer group.
     * @required
     * @maps customer_group
     * @var string $customerGroup public property
     */
    public $customerGroup;

    /**
     * Quantity.
     * @required
     * @var double $quantity public property
     */
    public $quantity;

    /**
     * ExtensionInterface class for @see \Magento\Catalog\Api\Data\TierPriceInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param double  $price               Initialization value for $this->price
     * @param string  $priceType           Initialization value for $this->priceType
     * @param integer $websiteId           Initialization value for $this->websiteId
     * @param string  $sku                 Initialization value for $this->sku
     * @param string  $customerGroup       Initialization value for $this->customerGroup
     * @param double  $quantity            Initialization value for $this->quantity
     * @param object  $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->price               = func_get_arg(0);
            $this->priceType           = func_get_arg(1);
            $this->websiteId           = func_get_arg(2);
            $this->sku                 = func_get_arg(3);
            $this->customerGroup       = func_get_arg(4);
            $this->quantity            = func_get_arg(5);
            $this->extensionAttributes = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['price']                = $this->price;
        $json['price_type']           = $this->priceType;
        $json['website_id']           = $this->websiteId;
        $json['sku']                  = $this->sku;
        $json['customer_group']       = $this->customerGroup;
        $json['quantity']             = $this->quantity;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
