<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogDataProductAttributeMediaGalleryEntryExtensionInterface implements JsonSerializable
{
    /**
     * Video Content data interface
     * @maps video_content
     * @var \MagentoCommunityLib\Models\FrameworkDataVideoContentInterface|null $videoContent public property
     */
    public $videoContent;

    /**
     * Constructor to set initial or default values of member properties
     * @param FrameworkDataVideoContentInterface $videoContent Initialization value for $this->videoContent
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->videoContent = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['video_content'] = $this->videoContent;

        return $json;
    }
}
