<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogDataProductWebsiteLinkInterface implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $sku public property
     */
    public $sku;

    /**
     * Website ids
     * @required
     * @maps website_id
     * @var integer $websiteId public property
     */
    public $websiteId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $sku       Initialization value for $this->sku
     * @param integer $websiteId Initialization value for $this->websiteId
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->sku       = func_get_arg(0);
            $this->websiteId = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['sku']        = $this->sku;
        $json['website_id'] = $this->websiteId;

        return $json;
    }
}
