<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogDataProductRenderExtensionInterface implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @maps review_html
     * @var string|null $reviewHtml public property
     */
    public $reviewHtml;

    /**
     * Button interface. This interface represents all manner of product buttons: add to cart, add to
     * compare, etc... The buttons describes by this interface should have interaction with backend
     * @maps wishlist_button
     * @var \MagentoCommunityLib\Models\CatalogDataProductRenderButtonInterface|null $wishlistButton public property
     */
    public $wishlistButton;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                                  $reviewHtml     Initialization value for $this->reviewHtml
     * @param CatalogDataProductRenderButtonInterface $wishlistButton Initialization value for $this->wishlistButton
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->reviewHtml     = func_get_arg(0);
            $this->wishlistButton = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['review_html']     = $this->reviewHtml;
        $json['wishlist_button'] = $this->wishlistButton;

        return $json;
    }
}
