<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogInventoryStockRegistryV1UpdateStockItemBySkuPutBody implements JsonSerializable
{
    /**
     * Interface StockItem
     * @required
     * @var \MagentoCommunityLib\Models\CatalogInventoryDataStockItemInterface $stockItem public property
     */
    public $stockItem;

    /**
     * Constructor to set initial or default values of member properties
     * @param CatalogInventoryDataStockItemInterface $stockItem Initialization value for $this->stockItem
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->stockItem = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['stockItem'] = $this->stockItem;

        return $json;
    }
}
