<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogDataCategoryInterface implements JsonSerializable
{
    /**
     * Category name
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @var integer|null $id public property
     */
    public $id;

    /**
     * Parent category ID
     * @maps parent_id
     * @var integer|null $parentId public property
     */
    public $parentId;

    /**
     * Whether category is active
     * @maps is_active
     * @var bool|null $isActive public property
     */
    public $isActive;

    /**
     * Category position
     * @var integer|null $position public property
     */
    public $position;

    /**
     * Category level
     * @var integer|null $level public property
     */
    public $level;

    /**
     * @todo Write general description for this property
     * @var string|null $children public property
     */
    public $children;

    /**
     * @todo Write general description for this property
     * @maps created_at
     * @var string|null $createdAt public property
     */
    public $createdAt;

    /**
     * @todo Write general description for this property
     * @maps updated_at
     * @var string|null $updatedAt public property
     */
    public $updatedAt;

    /**
     * @todo Write general description for this property
     * @var string|null $path public property
     */
    public $path;

    /**
     * @todo Write general description for this property
     * @maps available_sort_by
     * @var array|null $availableSortBy public property
     */
    public $availableSortBy;

    /**
     * @todo Write general description for this property
     * @maps include_in_menu
     * @var bool|null $includeInMenu public property
     */
    public $includeInMenu;

    /**
     * ExtensionInterface class for @see \Magento\Catalog\Api\Data\CategoryInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Custom attributes values.
     * @maps custom_attributes
     * @var \MagentoCommunityLib\Models\FrameworkAttributeInterface[]|null $customAttributes public property
     */
    public $customAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $name                Initialization value for $this->name
     * @param integer $id                  Initialization value for $this->id
     * @param integer $parentId            Initialization value for $this->parentId
     * @param bool    $isActive            Initialization value for $this->isActive
     * @param integer $position            Initialization value for $this->position
     * @param integer $level               Initialization value for $this->level
     * @param string  $children            Initialization value for $this->children
     * @param string  $createdAt           Initialization value for $this->createdAt
     * @param string  $updatedAt           Initialization value for $this->updatedAt
     * @param string  $path                Initialization value for $this->path
     * @param array   $availableSortBy     Initialization value for $this->availableSortBy
     * @param bool    $includeInMenu       Initialization value for $this->includeInMenu
     * @param object  $extensionAttributes Initialization value for $this->extensionAttributes
     * @param array   $customAttributes    Initialization value for $this->customAttributes
     */
    public function __construct()
    {
        if (14 == func_num_args()) {
            $this->name                = func_get_arg(0);
            $this->id                  = func_get_arg(1);
            $this->parentId            = func_get_arg(2);
            $this->isActive            = func_get_arg(3);
            $this->position            = func_get_arg(4);
            $this->level               = func_get_arg(5);
            $this->children            = func_get_arg(6);
            $this->createdAt           = func_get_arg(7);
            $this->updatedAt           = func_get_arg(8);
            $this->path                = func_get_arg(9);
            $this->availableSortBy     = func_get_arg(10);
            $this->includeInMenu       = func_get_arg(11);
            $this->extensionAttributes = func_get_arg(12);
            $this->customAttributes    = func_get_arg(13);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']                 = $this->name;
        $json['id']                   = $this->id;
        $json['parent_id']            = $this->parentId;
        $json['is_active']            = $this->isActive;
        $json['position']             = $this->position;
        $json['level']                = $this->level;
        $json['children']             = $this->children;
        $json['created_at']           = $this->createdAt;
        $json['updated_at']           = $this->updatedAt;
        $json['path']                 = $this->path;
        $json['available_sort_by']    = $this->availableSortBy;
        $json['include_in_menu']      = $this->includeInMenu;
        $json['extension_attributes'] = $this->extensionAttributes;
        $json['custom_attributes']    = $this->customAttributes;

        return $json;
    }
}
