<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogDataProductCustomOptionValuesInterface implements JsonSerializable
{
    /**
     * Option title
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * Sort order
     * @required
     * @maps sort_order
     * @var integer $sortOrder public property
     */
    public $sortOrder;

    /**
     * Price
     * @required
     * @var double $price public property
     */
    public $price;

    /**
     * Price type
     * @required
     * @maps price_type
     * @var string $priceType public property
     */
    public $priceType;

    /**
     * Sku
     * @var string|null $sku public property
     */
    public $sku;

    /**
     * Option type id
     * @maps option_type_id
     * @var integer|null $optionTypeId public property
     */
    public $optionTypeId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $title        Initialization value for $this->title
     * @param integer $sortOrder    Initialization value for $this->sortOrder
     * @param double  $price        Initialization value for $this->price
     * @param string  $priceType    Initialization value for $this->priceType
     * @param string  $sku          Initialization value for $this->sku
     * @param integer $optionTypeId Initialization value for $this->optionTypeId
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->title        = func_get_arg(0);
            $this->sortOrder    = func_get_arg(1);
            $this->price        = func_get_arg(2);
            $this->priceType    = func_get_arg(3);
            $this->sku          = func_get_arg(4);
            $this->optionTypeId = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['title']          = $this->title;
        $json['sort_order']     = $this->sortOrder;
        $json['price']          = $this->price;
        $json['price_type']     = $this->priceType;
        $json['sku']            = $this->sku;
        $json['option_type_id'] = $this->optionTypeId;

        return $json;
    }
}
