<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Cost interface.
 */
class CatalogDataCostInterface implements JsonSerializable
{
    /**
     * Cost value.
     * @required
     * @var double $cost public property
     */
    public $cost;

    /**
     * Store id.
     * @required
     * @maps store_id
     * @var integer $storeId public property
     */
    public $storeId;

    /**
     * SKU.
     * @required
     * @var string $sku public property
     */
    public $sku;

    /**
     * ExtensionInterface class for @see \Magento\Catalog\Api\Data\CostInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param double  $cost                Initialization value for $this->cost
     * @param integer $storeId             Initialization value for $this->storeId
     * @param string  $sku                 Initialization value for $this->sku
     * @param object  $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->cost                = func_get_arg(0);
            $this->storeId             = func_get_arg(1);
            $this->sku                 = func_get_arg(2);
            $this->extensionAttributes = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['cost']                 = $this->cost;
        $json['store_id']             = $this->storeId;
        $json['sku']                  = $this->sku;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
