<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogDataProductLinkAttributeInterface implements JsonSerializable
{
    /**
     * Attribute code
     * @required
     * @var string $code public property
     */
    public $code;

    /**
     * Attribute type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * ExtensionInterface class for @see \Magento\Catalog\Api\Data\ProductLinkAttributeInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $code                Initialization value for $this->code
     * @param string $type                Initialization value for $this->type
     * @param object $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->code                = func_get_arg(0);
            $this->type                = func_get_arg(1);
            $this->extensionAttributes = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['code']                 = $this->code;
        $json['type']                 = $this->type;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
