<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogDataCategoryTreeInterface implements JsonSerializable
{
    /**
     * Parent category ID
     * @required
     * @maps parent_id
     * @var integer $parentId public property
     */
    public $parentId;

    /**
     * Category name
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Whether category is active
     * @required
     * @maps is_active
     * @var bool $isActive public property
     */
    public $isActive;

    /**
     * Category position
     * @required
     * @var integer $position public property
     */
    public $position;

    /**
     * Category level
     * @required
     * @var integer $level public property
     */
    public $level;

    /**
     * Product count
     * @required
     * @maps product_count
     * @var integer $productCount public property
     */
    public $productCount;

    /**
     * @todo Write general description for this property
     * @required
     * @maps children_data
     * @var \MagentoCommunityLib\Models\CatalogDataCategoryTreeInterface[] $childrenData public property
     */
    public $childrenData;

    /**
     * @todo Write general description for this property
     * @var integer|null $id public property
     */
    public $id;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $parentId     Initialization value for $this->parentId
     * @param string  $name         Initialization value for $this->name
     * @param bool    $isActive     Initialization value for $this->isActive
     * @param integer $position     Initialization value for $this->position
     * @param integer $level        Initialization value for $this->level
     * @param integer $productCount Initialization value for $this->productCount
     * @param array   $childrenData Initialization value for $this->childrenData
     * @param integer $id           Initialization value for $this->id
     */
    public function __construct()
    {
        if (8 == func_num_args()) {
            $this->parentId     = func_get_arg(0);
            $this->name         = func_get_arg(1);
            $this->isActive     = func_get_arg(2);
            $this->position     = func_get_arg(3);
            $this->level        = func_get_arg(4);
            $this->productCount = func_get_arg(5);
            $this->childrenData = func_get_arg(6);
            $this->id           = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['parent_id']     = $this->parentId;
        $json['name']          = $this->name;
        $json['is_active']     = $this->isActive;
        $json['position']      = $this->position;
        $json['level']         = $this->level;
        $json['product_count'] = $this->productCount;
        $json['children_data'] = $this->childrenData;
        $json['id']            = $this->id;

        return $json;
    }
}
