<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogProductAttributeMediaGalleryManagementV1UpdatePutBody implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var \MagentoCommunityLib\Models\CatalogDataProductAttributeMediaGalleryEntryInterface $entry public property
     */
    public $entry;

    /**
     * Constructor to set initial or default values of member properties
     * @param CatalogDataProductAttributeMediaGalleryEntryInterface $entry Initialization value for $this->entry
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->entry = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['entry'] = $this->entry;

        return $json;
    }
}
