<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CatalogDataProductAttributeTypeInterface implements JsonSerializable
{
    /**
     * Value
     * @required
     * @var string $value public property
     */
    public $value;

    /**
     * Type label
     * @required
     * @var string $label public property
     */
    public $label;

    /**
     * ExtensionInterface class for @see \Magento\Catalog\Api\Data\ProductAttributeTypeInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $value               Initialization value for $this->value
     * @param string $label               Initialization value for $this->label
     * @param object $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->value               = func_get_arg(0);
            $this->label               = func_get_arg(1);
            $this->extensionAttributes = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['value']                = $this->value;
        $json['label']                = $this->label;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
