<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CheckoutGuestShippingInformationManagementV1SaveAddressInformationPostBody implements JsonSerializable
{
    /**
     * Interface ShippingInformationInterface
     * @required
     * @var \MagentoCommunityLib\Models\CheckoutDataShippingInformationInterface $addressInformation public property
     */
    public $addressInformation;

    /**
     * Constructor to set initial or default values of member properties
     * @param CheckoutDataShippingInformationInterface $addressInformation Initialization value for $this-
     *                                                                       >addressInformation
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->addressInformation = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['addressInformation'] = $this->addressInformation;

        return $json;
    }
}
