<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CmsBlockRepositoryV1SavePostBody implements JsonSerializable
{
    /**
     * CMS block interface.
     * @required
     * @var \MagentoCommunityLib\Models\CmsDataBlockInterface $block public property
     */
    public $block;

    /**
     * Constructor to set initial or default values of member properties
     * @param CmsDataBlockInterface $block Initialization value for $this->block
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->block = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['block'] = $this->block;

        return $json;
    }
}
