<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *CMS block interface.
 */
class CmsDataBlockInterface implements JsonSerializable
{
    /**
     * Identifier
     * @required
     * @var string $identifier public property
     */
    public $identifier;

    /**
     * ID
     * @var integer|null $id public property
     */
    public $id;

    /**
     * Title
     * @var string|null $title public property
     */
    public $title;

    /**
     * Content
     * @var string|null $content public property
     */
    public $content;

    /**
     * Creation time
     * @maps creation_time
     * @var string|null $creationTime public property
     */
    public $creationTime;

    /**
     * Update time
     * @maps update_time
     * @var string|null $updateTime public property
     */
    public $updateTime;

    /**
     * Active
     * @var bool|null $active public property
     */
    public $active;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $identifier   Initialization value for $this->identifier
     * @param integer $id           Initialization value for $this->id
     * @param string  $title        Initialization value for $this->title
     * @param string  $content      Initialization value for $this->content
     * @param string  $creationTime Initialization value for $this->creationTime
     * @param string  $updateTime   Initialization value for $this->updateTime
     * @param bool    $active       Initialization value for $this->active
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->identifier   = func_get_arg(0);
            $this->id           = func_get_arg(1);
            $this->title        = func_get_arg(2);
            $this->content      = func_get_arg(3);
            $this->creationTime = func_get_arg(4);
            $this->updateTime   = func_get_arg(5);
            $this->active       = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['identifier']    = $this->identifier;
        $json['id']            = $this->id;
        $json['title']         = $this->title;
        $json['content']       = $this->content;
        $json['creation_time'] = $this->creationTime;
        $json['update_time']   = $this->updateTime;
        $json['active']        = $this->active;

        return $json;
    }
}
