<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ConfigurableProductLinkManagementV1AddChildPostBody implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $childSku public property
     */
    public $childSku;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $childSku Initialization value for $this->childSku
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->childSku = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['childSku'] = $this->childSku;

        return $json;
    }
}
