<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ConfigurableProductOptionRepositoryV1SavePutBody implements JsonSerializable
{
    /**
     * Interface OptionInterface
     * @required
     * @var \MagentoCommunityLib\Models\ConfigurableProductDataOptionInterface $option public property
     */
    public $option;

    /**
     * Constructor to set initial or default values of member properties
     * @param ConfigurableProductDataOptionInterface $option Initialization value for $this->option
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->option = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['option'] = $this->option;

        return $json;
    }
}
