<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Customer interface.
 */
class CustomerDataCustomerInterface implements JsonSerializable
{
    /**
     * Email address
     * @required
     * @var string $email public property
     */
    public $email;

    /**
     * First name
     * @required
     * @var string $firstname public property
     */
    public $firstname;

    /**
     * Last name
     * @required
     * @var string $lastname public property
     */
    public $lastname;

    /**
     * Customer id
     * @var integer|null $id public property
     */
    public $id;

    /**
     * Group id
     * @maps group_id
     * @var integer|null $groupId public property
     */
    public $groupId;

    /**
     * Default billing address id
     * @maps default_billing
     * @var string|null $defaultBilling public property
     */
    public $defaultBilling;

    /**
     * Default shipping address id
     * @maps default_shipping
     * @var string|null $defaultShipping public property
     */
    public $defaultShipping;

    /**
     * Confirmation
     * @var string|null $confirmation public property
     */
    public $confirmation;

    /**
     * Created at time
     * @maps created_at
     * @var string|null $createdAt public property
     */
    public $createdAt;

    /**
     * Updated at time
     * @maps updated_at
     * @var string|null $updatedAt public property
     */
    public $updatedAt;

    /**
     * Created in area
     * @maps created_in
     * @var string|null $createdIn public property
     */
    public $createdIn;

    /**
     * Date of birth
     * @var string|null $dob public property
     */
    public $dob;

    /**
     * Middle name
     * @var string|null $middlename public property
     */
    public $middlename;

    /**
     * Prefix
     * @var string|null $prefix public property
     */
    public $prefix;

    /**
     * Suffix
     * @var string|null $suffix public property
     */
    public $suffix;

    /**
     * Gender
     * @var integer|null $gender public property
     */
    public $gender;

    /**
     * Store id
     * @maps store_id
     * @var integer|null $storeId public property
     */
    public $storeId;

    /**
     * Tax Vat
     * @var string|null $taxvat public property
     */
    public $taxvat;

    /**
     * Website id
     * @maps website_id
     * @var integer|null $websiteId public property
     */
    public $websiteId;

    /**
     * Customer addresses.
     * @var \MagentoCommunityLib\Models\CustomerDataAddressInterface[]|null $addresses public property
     */
    public $addresses;

    /**
     * Disable auto group change flag.
     * @maps disable_auto_group_change
     * @var integer|null $disableAutoGroupChange public property
     */
    public $disableAutoGroupChange;

    /**
     * ExtensionInterface class for @see \Magento\Customer\Api\Data\CustomerInterface
     * @maps extension_attributes
     * @var \MagentoCommunityLib\Models\CustomerDataCustomerExtensionInterface|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Custom attributes values.
     * @maps custom_attributes
     * @var \MagentoCommunityLib\Models\FrameworkAttributeInterface[]|null $customAttributes public property
     */
    public $customAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                                 $email                  Initialization value for $this->email
     * @param string                                 $firstname              Initialization value for $this-
     *                                                                         >firstname
     * @param string                                 $lastname               Initialization value for $this->lastname
     * @param integer                                $id                     Initialization value for $this->id
     * @param integer                                $groupId                Initialization value for $this->groupId
     * @param string                                 $defaultBilling         Initialization value for $this-
     *                                                                         >defaultBilling
     * @param string                                 $defaultShipping        Initialization value for $this-
     *                                                                         >defaultShipping
     * @param string                                 $confirmation           Initialization value for $this-
     *                                                                         >confirmation
     * @param string                                 $createdAt              Initialization value for $this-
     *                                                                         >createdAt
     * @param string                                 $updatedAt              Initialization value for $this-
     *                                                                         >updatedAt
     * @param string                                 $createdIn              Initialization value for $this-
     *                                                                         >createdIn
     * @param string                                 $dob                    Initialization value for $this->dob
     * @param string                                 $middlename             Initialization value for $this-
     *                                                                         >middlename
     * @param string                                 $prefix                 Initialization value for $this->prefix
     * @param string                                 $suffix                 Initialization value for $this->suffix
     * @param integer                                $gender                 Initialization value for $this->gender
     * @param integer                                $storeId                Initialization value for $this->storeId
     * @param string                                 $taxvat                 Initialization value for $this->taxvat
     * @param integer                                $websiteId              Initialization value for $this-
     *                                                                         >websiteId
     * @param array                                  $addresses              Initialization value for $this-
     *                                                                         >addresses
     * @param integer                                $disableAutoGroupChange Initialization value for $this-
     *                                                                         >disableAutoGroupChange
     * @param CustomerDataCustomerExtensionInterface $extensionAttributes    Initialization value for $this-
     *                                                                         >extensionAttributes
     * @param array                                  $customAttributes       Initialization value for $this-
     *                                                                         >customAttributes
     */
    public function __construct()
    {
        if (23 == func_num_args()) {
            $this->email                  = func_get_arg(0);
            $this->firstname              = func_get_arg(1);
            $this->lastname               = func_get_arg(2);
            $this->id                     = func_get_arg(3);
            $this->groupId                = func_get_arg(4);
            $this->defaultBilling         = func_get_arg(5);
            $this->defaultShipping        = func_get_arg(6);
            $this->confirmation           = func_get_arg(7);
            $this->createdAt              = func_get_arg(8);
            $this->updatedAt              = func_get_arg(9);
            $this->createdIn              = func_get_arg(10);
            $this->dob                    = func_get_arg(11);
            $this->middlename             = func_get_arg(12);
            $this->prefix                 = func_get_arg(13);
            $this->suffix                 = func_get_arg(14);
            $this->gender                 = func_get_arg(15);
            $this->storeId                = func_get_arg(16);
            $this->taxvat                 = func_get_arg(17);
            $this->websiteId              = func_get_arg(18);
            $this->addresses              = func_get_arg(19);
            $this->disableAutoGroupChange = func_get_arg(20);
            $this->extensionAttributes    = func_get_arg(21);
            $this->customAttributes       = func_get_arg(22);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['email']                     = $this->email;
        $json['firstname']                 = $this->firstname;
        $json['lastname']                  = $this->lastname;
        $json['id']                        = $this->id;
        $json['group_id']                  = $this->groupId;
        $json['default_billing']           = $this->defaultBilling;
        $json['default_shipping']          = $this->defaultShipping;
        $json['confirmation']              = $this->confirmation;
        $json['created_at']                = $this->createdAt;
        $json['updated_at']                = $this->updatedAt;
        $json['created_in']                = $this->createdIn;
        $json['dob']                       = $this->dob;
        $json['middlename']                = $this->middlename;
        $json['prefix']                    = $this->prefix;
        $json['suffix']                    = $this->suffix;
        $json['gender']                    = $this->gender;
        $json['store_id']                  = $this->storeId;
        $json['taxvat']                    = $this->taxvat;
        $json['website_id']                = $this->websiteId;
        $json['addresses']                 = $this->addresses;
        $json['disable_auto_group_change'] = $this->disableAutoGroupChange;
        $json['extension_attributes']      = $this->extensionAttributes;
        $json['custom_attributes']         = $this->customAttributes;

        return $json;
    }
}
