<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Option interface.
 */
class CustomerDataOptionInterface implements JsonSerializable
{
    /**
     * Option label
     * @required
     * @var string $label public property
     */
    public $label;

    /**
     * Option value
     * @var string|null $value public property
     */
    public $value;

    /**
     * Nested options
     * @var \MagentoCommunityLib\Models\CustomerDataOptionInterface[]|null $options public property
     */
    public $options;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $label   Initialization value for $this->label
     * @param string $value   Initialization value for $this->value
     * @param array  $options Initialization value for $this->options
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->label   = func_get_arg(0);
            $this->value   = func_get_arg(1);
            $this->options = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['label']   = $this->label;
        $json['value']   = $this->value;
        $json['options'] = $this->options;

        return $json;
    }
}
