<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CustomerAccountManagementV1ValidatePutBody implements JsonSerializable
{
    /**
     * Customer interface.
     * @required
     * @var \MagentoCommunityLib\Models\CustomerDataCustomerInterface $customer public property
     */
    public $customer;

    /**
     * Constructor to set initial or default values of member properties
     * @param CustomerDataCustomerInterface $customer Initialization value for $this->customer
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->customer = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['customer'] = $this->customer;

        return $json;
    }
}
