<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CustomerAccountManagementV1CreateAccountPostBody implements JsonSerializable
{
    /**
     * Customer interface.
     * @required
     * @var \MagentoCommunityLib\Models\CustomerDataCustomerInterface $customer public property
     */
    public $customer;

    /**
     * @todo Write general description for this property
     * @var string|null $password public property
     */
    public $password;

    /**
     * @todo Write general description for this property
     * @var string|null $redirectUrl public property
     */
    public $redirectUrl;

    /**
     * Constructor to set initial or default values of member properties
     * @param CustomerDataCustomerInterface $customer    Initialization value for $this->customer
     * @param string                        $password    Initialization value for $this->password
     * @param string                        $redirectUrl Initialization value for $this->redirectUrl
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->customer    = func_get_arg(0);
            $this->password    = func_get_arg(1);
            $this->redirectUrl = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['customer']    = $this->customer;
        $json['password']    = $this->password;
        $json['redirectUrl'] = $this->redirectUrl;

        return $json;
    }
}
