<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CustomerDataRegionInterface implements JsonSerializable
{
    /**
     * Region code
     * @required
     * @maps region_code
     * @var string $regionCode public property
     */
    public $regionCode;

    /**
     * Region
     * @required
     * @var string $region public property
     */
    public $region;

    /**
     * Region id
     * @required
     * @maps region_id
     * @var integer $regionId public property
     */
    public $regionId;

    /**
     * ExtensionInterface class for @see \Magento\Customer\Api\Data\RegionInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $regionCode          Initialization value for $this->regionCode
     * @param string  $region              Initialization value for $this->region
     * @param integer $regionId            Initialization value for $this->regionId
     * @param object  $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->regionCode          = func_get_arg(0);
            $this->region              = func_get_arg(1);
            $this->regionId            = func_get_arg(2);
            $this->extensionAttributes = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['region_code']          = $this->regionCode;
        $json['region']               = $this->region;
        $json['region_id']            = $this->regionId;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
