<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Country Information interface.
 */
class DirectoryDataCountryInformationInterface implements JsonSerializable
{
    /**
     * The country id for the store.
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * The country 2 letter abbreviation for the store.
     * @required
     * @maps two_letter_abbreviation
     * @var string $twoLetterAbbreviation public property
     */
    public $twoLetterAbbreviation;

    /**
     * The country 3 letter abbreviation for the store.
     * @required
     * @maps three_letter_abbreviation
     * @var string $threeLetterAbbreviation public property
     */
    public $threeLetterAbbreviation;

    /**
     * The country full name (in store locale) for the store.
     * @required
     * @maps full_name_locale
     * @var string $fullNameLocale public property
     */
    public $fullNameLocale;

    /**
     * The country full name (in English) for the store.
     * @required
     * @maps full_name_english
     * @var string $fullNameEnglish public property
     */
    public $fullNameEnglish;

    /**
     * The available regions for the store.
     * @maps available_regions
     * @var \MagentoCommunityLib\Models\DirectoryDataRegionInformationInterface[]|null $availableRegions public property
     */
    public $availableRegions;

    /**
     * ExtensionInterface class for @see \Magento\Directory\Api\Data\CountryInformationInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $id                      Initialization value for $this->id
     * @param string $twoLetterAbbreviation   Initialization value for $this->twoLetterAbbreviation
     * @param string $threeLetterAbbreviation Initialization value for $this->threeLetterAbbreviation
     * @param string $fullNameLocale          Initialization value for $this->fullNameLocale
     * @param string $fullNameEnglish         Initialization value for $this->fullNameEnglish
     * @param array  $availableRegions        Initialization value for $this->availableRegions
     * @param object $extensionAttributes     Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->id                      = func_get_arg(0);
            $this->twoLetterAbbreviation   = func_get_arg(1);
            $this->threeLetterAbbreviation = func_get_arg(2);
            $this->fullNameLocale          = func_get_arg(3);
            $this->fullNameEnglish         = func_get_arg(4);
            $this->availableRegions        = func_get_arg(5);
            $this->extensionAttributes     = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                        = $this->id;
        $json['two_letter_abbreviation']   = $this->twoLetterAbbreviation;
        $json['three_letter_abbreviation'] = $this->threeLetterAbbreviation;
        $json['full_name_locale']          = $this->fullNameLocale;
        $json['full_name_english']         = $this->fullNameEnglish;
        $json['available_regions']         = $this->availableRegions;
        $json['extension_attributes']      = $this->extensionAttributes;

        return $json;
    }
}
