<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DownloadableDataFileContentInterface implements JsonSerializable
{
    /**
     * Data (base64 encoded content)
     * @required
     * @maps file_data
     * @var string $fileData public property
     */
    public $fileData;

    /**
     * File name
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * ExtensionInterface class for @see \Magento\Downloadable\Api\Data\File\ContentInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $fileData            Initialization value for $this->fileData
     * @param string $name                Initialization value for $this->name
     * @param object $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->fileData            = func_get_arg(0);
            $this->name                = func_get_arg(1);
            $this->extensionAttributes = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['file_data']            = $this->fileData;
        $json['name']                 = $this->name;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
