<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DownloadableLinkRepositoryV1SavePostBody implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var \MagentoCommunityLib\Models\DownloadableDataLinkInterface $link public property
     */
    public $link;

    /**
     * @todo Write general description for this property
     * @var bool|null $isGlobalScopeContent public property
     */
    public $isGlobalScopeContent;

    /**
     * Constructor to set initial or default values of member properties
     * @param DownloadableDataLinkInterface $link                 Initialization value for $this->link
     * @param bool                          $isGlobalScopeContent Initialization value for $this-
     *                                                              >isGlobalScopeContent
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->link                 = func_get_arg(0);
            $this->isGlobalScopeContent = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['link']                 = $this->link;
        $json['isGlobalScopeContent'] = $this->isGlobalScopeContent;

        return $json;
    }
}
