<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Interface \Magento\Framework\Api\Search\AggregationValueInterface
 */
class FrameworkSearchAggregationValueInterface implements JsonSerializable
{
    /**
     * Aggregation
     * @required
     * @var string $value public property
     */
    public $value;

    /**
     * Metrics
     * @required
     * @var array $metrics public property
     */
    public $metrics;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $value   Initialization value for $this->value
     * @param array  $metrics Initialization value for $this->metrics
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->value   = func_get_arg(0);
            $this->metrics = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['value']   = $this->value;
        $json['metrics'] = $this->metrics;

        return $json;
    }
}
