<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Interface SearchResultInterface
 */
class FrameworkSearchSearchResultInterface implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var \MagentoCommunityLib\Models\FrameworkSearchDocumentInterface[] $items public property
     */
    public $items;

    /**
     * Faceted data
     * @required
     * @var \MagentoCommunityLib\Models\FrameworkSearchAggregationInterface $aggregations public property
     */
    public $aggregations;

    /**
     * Interface SearchCriteriaInterface
     * @required
     * @maps search_criteria
     * @var \MagentoCommunityLib\Models\FrameworkSearchSearchCriteriaInterface $searchCriteria public property
     */
    public $searchCriteria;

    /**
     * Total count.
     * @required
     * @maps total_count
     * @var integer $totalCount public property
     */
    public $totalCount;

    /**
     * Constructor to set initial or default values of member properties
     * @param array                                  $items          Initialization value for $this->items
     * @param FrameworkSearchAggregationInterface    $aggregations   Initialization value for $this->aggregations
     * @param FrameworkSearchSearchCriteriaInterface $searchCriteria Initialization value for $this->searchCriteria
     * @param integer                                $totalCount     Initialization value for $this->totalCount
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->items          = func_get_arg(0);
            $this->aggregations   = func_get_arg(1);
            $this->searchCriteria = func_get_arg(2);
            $this->totalCount     = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['items']           = $this->items;
        $json['aggregations']    = $this->aggregations;
        $json['search_criteria'] = $this->searchCriteria;
        $json['total_count']     = $this->totalCount;

        return $json;
    }
}
