<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class FrameworkSearchSearchCriteriaInterface implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps request_name
     * @var string $requestName public property
     */
    public $requestName;

    /**
     * A list of filter groups.
     * @required
     * @maps filter_groups
     * @var \MagentoCommunityLib\Models\FrameworkSearchFilterGroup[] $filterGroups public property
     */
    public $filterGroups;

    /**
     * Sort order.
     * @maps sort_orders
     * @var \MagentoCommunityLib\Models\FrameworkSortOrder[]|null $sortOrders public property
     */
    public $sortOrders;

    /**
     * Page size.
     * @maps page_size
     * @var integer|null $pageSize public property
     */
    public $pageSize;

    /**
     * Current page.
     * @maps current_page
     * @var integer|null $currentPage public property
     */
    public $currentPage;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $requestName  Initialization value for $this->requestName
     * @param array   $filterGroups Initialization value for $this->filterGroups
     * @param array   $sortOrders   Initialization value for $this->sortOrders
     * @param integer $pageSize     Initialization value for $this->pageSize
     * @param integer $currentPage  Initialization value for $this->currentPage
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->requestName  = func_get_arg(0);
            $this->filterGroups = func_get_arg(1);
            $this->sortOrders   = func_get_arg(2);
            $this->pageSize     = func_get_arg(3);
            $this->currentPage  = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['request_name']  = $this->requestName;
        $json['filter_groups'] = $this->filterGroups;
        $json['sort_orders']   = $this->sortOrders;
        $json['page_size']     = $this->pageSize;
        $json['current_page']  = $this->currentPage;

        return $json;
    }
}
