<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Interface for custom attribute value.
 */
class FrameworkAttributeInterface implements JsonSerializable
{
    /**
     * Attribute code
     * @required
     * @maps attribute_code
     * @var string $attributeCode public property
     */
    public $attributeCode;

    /**
     * Attribute value
     * @required
     * @var string $value public property
     */
    public $value;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $attributeCode Initialization value for $this->attributeCode
     * @param string $value         Initialization value for $this->value
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->attributeCode = func_get_arg(0);
            $this->value         = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['attribute_code'] = $this->attributeCode;
        $json['value']          = $this->value;

        return $json;
    }
}
