<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class MsrpDataProductRenderMsrpPriceInfoInterface implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps msrp_price
     * @var string $msrpPrice public property
     */
    public $msrpPrice;

    /**
     * @todo Write general description for this property
     * @required
     * @maps is_applicable
     * @var string $isApplicable public property
     */
    public $isApplicable;

    /**
     * @todo Write general description for this property
     * @required
     * @maps is_shown_price_on_gesture
     * @var string $isShownPriceOnGesture public property
     */
    public $isShownPriceOnGesture;

    /**
     * @todo Write general description for this property
     * @required
     * @maps msrp_message
     * @var string $msrpMessage public property
     */
    public $msrpMessage;

    /**
     * @todo Write general description for this property
     * @required
     * @maps explanation_message
     * @var string $explanationMessage public property
     */
    public $explanationMessage;

    /**
     * ExtensionInterface class for @see \Magento\Msrp\Api\Data\ProductRender\MsrpPriceInfoInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $msrpPrice             Initialization value for $this->msrpPrice
     * @param string $isApplicable          Initialization value for $this->isApplicable
     * @param string $isShownPriceOnGesture Initialization value for $this->isShownPriceOnGesture
     * @param string $msrpMessage           Initialization value for $this->msrpMessage
     * @param string $explanationMessage    Initialization value for $this->explanationMessage
     * @param object $extensionAttributes   Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->msrpPrice             = func_get_arg(0);
            $this->isApplicable          = func_get_arg(1);
            $this->isShownPriceOnGesture = func_get_arg(2);
            $this->msrpMessage           = func_get_arg(3);
            $this->explanationMessage    = func_get_arg(4);
            $this->extensionAttributes   = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['msrp_price']                = $this->msrpPrice;
        $json['is_applicable']             = $this->isApplicable;
        $json['is_shown_price_on_gesture'] = $this->isShownPriceOnGesture;
        $json['msrp_message']              = $this->msrpMessage;
        $json['explanation_message']       = $this->explanationMessage;
        $json['extension_attributes']      = $this->extensionAttributes;

        return $json;
    }
}
