<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Interface ShippingAssignmentInterface
 */
class QuoteDataShippingAssignmentInterface implements JsonSerializable
{
    /**
     * Interface ShippingInterface
     * @required
     * @var \MagentoCommunityLib\Models\QuoteDataShippingInterface $shipping public property
     */
    public $shipping;

    /**
     * @todo Write general description for this property
     * @required
     * @var \MagentoCommunityLib\Models\QuoteDataCartItemInterface[] $items public property
     */
    public $items;

    /**
     * ExtensionInterface class for @see \Magento\Quote\Api\Data\ShippingAssignmentInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param QuoteDataShippingInterface $shipping            Initialization value for $this->shipping
     * @param array                      $items               Initialization value for $this->items
     * @param object                     $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->shipping            = func_get_arg(0);
            $this->items               = func_get_arg(1);
            $this->extensionAttributes = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['shipping']             = $this->shipping;
        $json['items']                = $this->items;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
