<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class QuoteDataTotalSegmentExtensionInterface implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @maps tax_grandtotal_details
     * @var \MagentoCommunityLib\Models\TaxDataGrandTotalDetailsInterface[]|null $taxGrandtotalDetails public property
     */
    public $taxGrandtotalDetails;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $taxGrandtotalDetails Initialization value for $this->taxGrandtotalDetails
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->taxGrandtotalDetails = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['tax_grandtotal_details'] = $this->taxGrandtotalDetails;

        return $json;
    }
}
