<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Additional data for totals collection.
 */
class QuoteDataTotalsAdditionalDataInterface implements JsonSerializable
{
    /**
     * ExtensionInterface class for @see \Magento\Quote\Api\Data\TotalsAdditionalDataInterface
     * @maps extension_attributes
     * @var \MagentoCommunityLib\Models\QuoteDataTotalsAdditionalDataExtensionInterface|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Custom attributes values.
     * @maps custom_attributes
     * @var \MagentoCommunityLib\Models\FrameworkAttributeInterface[]|null $customAttributes public property
     */
    public $customAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param QuoteDataTotalsAdditionalDataExtensionInterface $extensionAttributes Initialization value for $this-
     *                                                                               >extensionAttributes
     * @param array                                           $customAttributes    Initialization value for $this-
     *                                                                               >customAttributes
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->extensionAttributes = func_get_arg(0);
            $this->customAttributes    = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['extension_attributes'] = $this->extensionAttributes;
        $json['custom_attributes']    = $this->customAttributes;

        return $json;
    }
}
