<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Interface PaymentInterface
 */
class QuoteDataPaymentInterface implements JsonSerializable
{
    /**
     * Payment method code
     * @required
     * @var string $method public property
     */
    public $method;

    /**
     * Purchase order number
     * @maps po_number
     * @var string|null $poNumber public property
     */
    public $poNumber;

    /**
     * Payment additional details
     * @maps additional_data
     * @var array|null $additionalData public property
     */
    public $additionalData;

    /**
     * ExtensionInterface class for @see \Magento\Quote\Api\Data\PaymentInterface
     * @maps extension_attributes
     * @var \MagentoCommunityLib\Models\QuoteDataPaymentExtensionInterface|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                             $method              Initialization value for $this->method
     * @param string                             $poNumber            Initialization value for $this->poNumber
     * @param array                              $additionalData      Initialization value for $this->additionalData
     * @param QuoteDataPaymentExtensionInterface $extensionAttributes Initialization value for $this-
     *                                                                  >extensionAttributes
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->method              = func_get_arg(0);
            $this->poNumber            = func_get_arg(1);
            $this->additionalData      = func_get_arg(2);
            $this->extensionAttributes = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['method']               = $this->method;
        $json['po_number']            = $this->poNumber;
        $json['additional_data']      = $this->additionalData;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
