<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class QuoteDataShippingInterface implements JsonSerializable
{
    /**
     * Interface AddressInterface
     * @required
     * @var \MagentoCommunityLib\Models\QuoteDataAddressInterface $address public property
     */
    public $address;

    /**
     * Shipping method
     * @required
     * @var string $method public property
     */
    public $method;

    /**
     * ExtensionInterface class for @see \Magento\Quote\Api\Data\ShippingInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param QuoteDataAddressInterface $address             Initialization value for $this->address
     * @param string                    $method              Initialization value for $this->method
     * @param object                    $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->address             = func_get_arg(0);
            $this->method              = func_get_arg(1);
            $this->extensionAttributes = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['address']              = $this->address;
        $json['method']               = $this->method;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
