<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class QuoteDataProductOptionInterface implements JsonSerializable
{
    /**
     * ExtensionInterface class for @see \Magento\Quote\Api\Data\ProductOptionInterface
     * @maps extension_attributes
     * @var \MagentoCommunityLib\Models\QuoteDataProductOptionExtensionInterface|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param QuoteDataProductOptionExtensionInterface $extensionAttributes Initialization value for $this-
     *                                                                        >extensionAttributes
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->extensionAttributes = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
