<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SalesDataShippingInterface implements JsonSerializable
{
    /**
     * Order address interface. An order is a document that a web store issues to a customer. Magento
     * generates a sales order that lists the product items, billing and shipping addresses, and shipping
     * and payment methods. A corresponding external document, known as a purchase order, is emailed to the
     * customer.
     * @var \MagentoCommunityLib\Models\SalesDataOrderAddressInterface|null $address public property
     */
    public $address;

    /**
     * Shipping method
     * @var string|null $method public property
     */
    public $method;

    /**
     * Interface TotalInterface
     * @var \MagentoCommunityLib\Models\SalesDataTotalInterface|null $total public property
     */
    public $total;

    /**
     * ExtensionInterface class for @see \Magento\Sales\Api\Data\ShippingInterface
     * @maps extension_attributes
     * @var \MagentoCommunityLib\Models\SalesDataShippingExtensionInterface|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param SalesDataOrderAddressInterface      $address             Initialization value for $this->address
     * @param string                              $method              Initialization value for $this->method
     * @param SalesDataTotalInterface             $total               Initialization value for $this->total
     * @param SalesDataShippingExtensionInterface $extensionAttributes Initialization value for $this-
     *                                                                   >extensionAttributes
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->address             = func_get_arg(0);
            $this->method              = func_get_arg(1);
            $this->total               = func_get_arg(2);
            $this->extensionAttributes = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['address']              = $this->address;
        $json['method']               = $this->method;
        $json['total']                = $this->total;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
