<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SalesRuleDataConditionInterface implements JsonSerializable
{
    /**
     * Condition type
     * @required
     * @maps condition_type
     * @var string $conditionType public property
     */
    public $conditionType;

    /**
     * The operator of the condition
     * @required
     * @var string $operator public property
     */
    public $operator;

    /**
     * The value of the condition
     * @required
     * @var string $value public property
     */
    public $value;

    /**
     * List of conditions
     * @var \MagentoCommunityLib\Models\SalesRuleDataConditionInterface[]|null $conditions public property
     */
    public $conditions;

    /**
     * The aggregator type
     * @maps aggregator_type
     * @var string|null $aggregatorType public property
     */
    public $aggregatorType;

    /**
     * The attribute name of the condition
     * @maps attribute_name
     * @var string|null $attributeName public property
     */
    public $attributeName;

    /**
     * ExtensionInterface class for @see \Magento\SalesRule\Api\Data\ConditionInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $conditionType       Initialization value for $this->conditionType
     * @param string $operator            Initialization value for $this->operator
     * @param string $value               Initialization value for $this->value
     * @param array  $conditions          Initialization value for $this->conditions
     * @param string $aggregatorType      Initialization value for $this->aggregatorType
     * @param string $attributeName       Initialization value for $this->attributeName
     * @param object $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->conditionType       = func_get_arg(0);
            $this->operator            = func_get_arg(1);
            $this->value               = func_get_arg(2);
            $this->conditions          = func_get_arg(3);
            $this->aggregatorType      = func_get_arg(4);
            $this->attributeName       = func_get_arg(5);
            $this->extensionAttributes = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['condition_type']       = $this->conditionType;
        $json['operator']             = $this->operator;
        $json['value']                = $this->value;
        $json['conditions']           = $this->conditions;
        $json['aggregator_type']      = $this->aggregatorType;
        $json['attribute_name']       = $this->attributeName;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
