<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Order interface. An order is a document that a web store issues to a customer. Magento generates a
 * sales order that lists the product items, billing and shipping addresses, and shipping and payment
 * methods. A corresponding external document, known as a purchase order, is emailed to the customer.
 */
class SalesDataOrderInterface implements JsonSerializable
{
    /**
     * Base grand total.
     * @required
     * @maps base_grand_total
     * @var double $baseGrandTotal public property
     */
    public $baseGrandTotal;

    /**
     * Customer email address.
     * @required
     * @maps customer_email
     * @var string $customerEmail public property
     */
    public $customerEmail;

    /**
     * Grand total.
     * @required
     * @maps grand_total
     * @var double $grandTotal public property
     */
    public $grandTotal;

    /**
     * Array of items.
     * @required
     * @var \MagentoCommunityLib\Models\SalesDataOrderItemInterface[] $items public property
     */
    public $items;

    /**
     * Negative adjustment value.
     * @maps adjustment_negative
     * @var double|null $adjustmentNegative public property
     */
    public $adjustmentNegative;

    /**
     * Positive adjustment value.
     * @maps adjustment_positive
     * @var double|null $adjustmentPositive public property
     */
    public $adjustmentPositive;

    /**
     * Applied rule IDs.
     * @maps applied_rule_ids
     * @var string|null $appliedRuleIds public property
     */
    public $appliedRuleIds;

    /**
     * Base negative adjustment value.
     * @maps base_adjustment_negative
     * @var double|null $baseAdjustmentNegative public property
     */
    public $baseAdjustmentNegative;

    /**
     * Base positive adjustment value.
     * @maps base_adjustment_positive
     * @var double|null $baseAdjustmentPositive public property
     */
    public $baseAdjustmentPositive;

    /**
     * Base currency code.
     * @maps base_currency_code
     * @var string|null $baseCurrencyCode public property
     */
    public $baseCurrencyCode;

    /**
     * Base discount amount.
     * @maps base_discount_amount
     * @var double|null $baseDiscountAmount public property
     */
    public $baseDiscountAmount;

    /**
     * Base discount canceled.
     * @maps base_discount_canceled
     * @var double|null $baseDiscountCanceled public property
     */
    public $baseDiscountCanceled;

    /**
     * Base discount invoiced.
     * @maps base_discount_invoiced
     * @var double|null $baseDiscountInvoiced public property
     */
    public $baseDiscountInvoiced;

    /**
     * Base discount refunded.
     * @maps base_discount_refunded
     * @var double|null $baseDiscountRefunded public property
     */
    public $baseDiscountRefunded;

    /**
     * Base discount tax compensation amount.
     * @maps base_discount_tax_compensation_amount
     * @var double|null $baseDiscountTaxCompensationAmount public property
     */
    public $baseDiscountTaxCompensationAmount;

    /**
     * Base discount tax compensation invoiced.
     * @maps base_discount_tax_compensation_invoiced
     * @var double|null $baseDiscountTaxCompensationInvoiced public property
     */
    public $baseDiscountTaxCompensationInvoiced;

    /**
     * Base discount tax compensation refunded.
     * @maps base_discount_tax_compensation_refunded
     * @var double|null $baseDiscountTaxCompensationRefunded public property
     */
    public $baseDiscountTaxCompensationRefunded;

    /**
     * Base shipping amount.
     * @maps base_shipping_amount
     * @var double|null $baseShippingAmount public property
     */
    public $baseShippingAmount;

    /**
     * Base shipping canceled.
     * @maps base_shipping_canceled
     * @var double|null $baseShippingCanceled public property
     */
    public $baseShippingCanceled;

    /**
     * Base shipping discount amount.
     * @maps base_shipping_discount_amount
     * @var double|null $baseShippingDiscountAmount public property
     */
    public $baseShippingDiscountAmount;

    /**
     * Base shipping discount tax compensation amount.
     * @maps base_shipping_discount_tax_compensation_amnt
     * @var double|null $baseShippingDiscountTaxCompensationAmnt public property
     */
    public $baseShippingDiscountTaxCompensationAmnt;

    /**
     * Base shipping including tax.
     * @maps base_shipping_incl_tax
     * @var double|null $baseShippingInclTax public property
     */
    public $baseShippingInclTax;

    /**
     * Base shipping invoiced.
     * @maps base_shipping_invoiced
     * @var double|null $baseShippingInvoiced public property
     */
    public $baseShippingInvoiced;

    /**
     * Base shipping refunded.
     * @maps base_shipping_refunded
     * @var double|null $baseShippingRefunded public property
     */
    public $baseShippingRefunded;

    /**
     * Base shipping tax amount.
     * @maps base_shipping_tax_amount
     * @var double|null $baseShippingTaxAmount public property
     */
    public $baseShippingTaxAmount;

    /**
     * Base shipping tax refunded.
     * @maps base_shipping_tax_refunded
     * @var double|null $baseShippingTaxRefunded public property
     */
    public $baseShippingTaxRefunded;

    /**
     * Base subtotal.
     * @maps base_subtotal
     * @var double|null $baseSubtotal public property
     */
    public $baseSubtotal;

    /**
     * Base subtotal canceled.
     * @maps base_subtotal_canceled
     * @var double|null $baseSubtotalCanceled public property
     */
    public $baseSubtotalCanceled;

    /**
     * Base subtotal including tax.
     * @maps base_subtotal_incl_tax
     * @var double|null $baseSubtotalInclTax public property
     */
    public $baseSubtotalInclTax;

    /**
     * Base subtotal invoiced.
     * @maps base_subtotal_invoiced
     * @var double|null $baseSubtotalInvoiced public property
     */
    public $baseSubtotalInvoiced;

    /**
     * Base subtotal refunded.
     * @maps base_subtotal_refunded
     * @var double|null $baseSubtotalRefunded public property
     */
    public $baseSubtotalRefunded;

    /**
     * Base tax amount.
     * @maps base_tax_amount
     * @var double|null $baseTaxAmount public property
     */
    public $baseTaxAmount;

    /**
     * Base tax canceled.
     * @maps base_tax_canceled
     * @var double|null $baseTaxCanceled public property
     */
    public $baseTaxCanceled;

    /**
     * Base tax invoiced.
     * @maps base_tax_invoiced
     * @var double|null $baseTaxInvoiced public property
     */
    public $baseTaxInvoiced;

    /**
     * Base tax refunded.
     * @maps base_tax_refunded
     * @var double|null $baseTaxRefunded public property
     */
    public $baseTaxRefunded;

    /**
     * Base total canceled.
     * @maps base_total_canceled
     * @var double|null $baseTotalCanceled public property
     */
    public $baseTotalCanceled;

    /**
     * Base total due.
     * @maps base_total_due
     * @var double|null $baseTotalDue public property
     */
    public $baseTotalDue;

    /**
     * Base total invoiced.
     * @maps base_total_invoiced
     * @var double|null $baseTotalInvoiced public property
     */
    public $baseTotalInvoiced;

    /**
     * Base total invoiced cost.
     * @maps base_total_invoiced_cost
     * @var double|null $baseTotalInvoicedCost public property
     */
    public $baseTotalInvoicedCost;

    /**
     * Base total offline refunded.
     * @maps base_total_offline_refunded
     * @var double|null $baseTotalOfflineRefunded public property
     */
    public $baseTotalOfflineRefunded;

    /**
     * Base total online refunded.
     * @maps base_total_online_refunded
     * @var double|null $baseTotalOnlineRefunded public property
     */
    public $baseTotalOnlineRefunded;

    /**
     * Base total paid.
     * @maps base_total_paid
     * @var double|null $baseTotalPaid public property
     */
    public $baseTotalPaid;

    /**
     * Base total quantity ordered.
     * @maps base_total_qty_ordered
     * @var double|null $baseTotalQtyOrdered public property
     */
    public $baseTotalQtyOrdered;

    /**
     * Base total refunded.
     * @maps base_total_refunded
     * @var double|null $baseTotalRefunded public property
     */
    public $baseTotalRefunded;

    /**
     * Base-to-global rate.
     * @maps base_to_global_rate
     * @var double|null $baseToGlobalRate public property
     */
    public $baseToGlobalRate;

    /**
     * Base-to-order rate.
     * @maps base_to_order_rate
     * @var double|null $baseToOrderRate public property
     */
    public $baseToOrderRate;

    /**
     * Billing address ID.
     * @maps billing_address_id
     * @var integer|null $billingAddressId public property
     */
    public $billingAddressId;

    /**
     * Can-ship-partially flag value.
     * @maps can_ship_partially
     * @var integer|null $canShipPartially public property
     */
    public $canShipPartially;

    /**
     * Can-ship-partially-item flag value.
     * @maps can_ship_partially_item
     * @var integer|null $canShipPartiallyItem public property
     */
    public $canShipPartiallyItem;

    /**
     * Coupon code.
     * @maps coupon_code
     * @var string|null $couponCode public property
     */
    public $couponCode;

    /**
     * Created-at timestamp.
     * @maps created_at
     * @var string|null $createdAt public property
     */
    public $createdAt;

    /**
     * Customer date-of-birth (DOB).
     * @maps customer_dob
     * @var string|null $customerDob public property
     */
    public $customerDob;

    /**
     * Customer first name.
     * @maps customer_firstname
     * @var string|null $customerFirstname public property
     */
    public $customerFirstname;

    /**
     * Customer gender.
     * @maps customer_gender
     * @var integer|null $customerGender public property
     */
    public $customerGender;

    /**
     * Customer group ID.
     * @maps customer_group_id
     * @var integer|null $customerGroupId public property
     */
    public $customerGroupId;

    /**
     * Customer ID.
     * @maps customer_id
     * @var integer|null $customerId public property
     */
    public $customerId;

    /**
     * Customer-is-guest flag value.
     * @maps customer_is_guest
     * @var integer|null $customerIsGuest public property
     */
    public $customerIsGuest;

    /**
     * Customer last name.
     * @maps customer_lastname
     * @var string|null $customerLastname public property
     */
    public $customerLastname;

    /**
     * Customer middle name.
     * @maps customer_middlename
     * @var string|null $customerMiddlename public property
     */
    public $customerMiddlename;

    /**
     * Customer note.
     * @maps customer_note
     * @var string|null $customerNote public property
     */
    public $customerNote;

    /**
     * Customer-note-notify flag value.
     * @maps customer_note_notify
     * @var integer|null $customerNoteNotify public property
     */
    public $customerNoteNotify;

    /**
     * Customer prefix.
     * @maps customer_prefix
     * @var string|null $customerPrefix public property
     */
    public $customerPrefix;

    /**
     * Customer suffix.
     * @maps customer_suffix
     * @var string|null $customerSuffix public property
     */
    public $customerSuffix;

    /**
     * Customer value-added tax (VAT).
     * @maps customer_taxvat
     * @var string|null $customerTaxvat public property
     */
    public $customerTaxvat;

    /**
     * Discount amount.
     * @maps discount_amount
     * @var double|null $discountAmount public property
     */
    public $discountAmount;

    /**
     * Discount canceled.
     * @maps discount_canceled
     * @var double|null $discountCanceled public property
     */
    public $discountCanceled;

    /**
     * Discount description.
     * @maps discount_description
     * @var string|null $discountDescription public property
     */
    public $discountDescription;

    /**
     * Discount invoiced.
     * @maps discount_invoiced
     * @var double|null $discountInvoiced public property
     */
    public $discountInvoiced;

    /**
     * Discount refunded amount.
     * @maps discount_refunded
     * @var double|null $discountRefunded public property
     */
    public $discountRefunded;

    /**
     * Edit increment value.
     * @maps edit_increment
     * @var integer|null $editIncrement public property
     */
    public $editIncrement;

    /**
     * Email-sent flag value.
     * @maps email_sent
     * @var integer|null $emailSent public property
     */
    public $emailSent;

    /**
     * Order ID.
     * @maps entity_id
     * @var integer|null $entityId public property
     */
    public $entityId;

    /**
     * External customer ID.
     * @maps ext_customer_id
     * @var string|null $extCustomerId public property
     */
    public $extCustomerId;

    /**
     * External order ID.
     * @maps ext_order_id
     * @var string|null $extOrderId public property
     */
    public $extOrderId;

    /**
     * Forced-shipment-with-invoice flag value.
     * @maps forced_shipment_with_invoice
     * @var integer|null $forcedShipmentWithInvoice public property
     */
    public $forcedShipmentWithInvoice;

    /**
     * Global currency code.
     * @maps global_currency_code
     * @var string|null $globalCurrencyCode public property
     */
    public $globalCurrencyCode;

    /**
     * Discount tax compensation amount.
     * @maps discount_tax_compensation_amount
     * @var double|null $discountTaxCompensationAmount public property
     */
    public $discountTaxCompensationAmount;

    /**
     * Discount tax compensation invoiced amount.
     * @maps discount_tax_compensation_invoiced
     * @var double|null $discountTaxCompensationInvoiced public property
     */
    public $discountTaxCompensationInvoiced;

    /**
     * Discount tax compensation refunded amount.
     * @maps discount_tax_compensation_refunded
     * @var double|null $discountTaxCompensationRefunded public property
     */
    public $discountTaxCompensationRefunded;

    /**
     * Hold before state.
     * @maps hold_before_state
     * @var string|null $holdBeforeState public property
     */
    public $holdBeforeState;

    /**
     * Hold before status.
     * @maps hold_before_status
     * @var string|null $holdBeforeStatus public property
     */
    public $holdBeforeStatus;

    /**
     * Increment ID.
     * @maps increment_id
     * @var string|null $incrementId public property
     */
    public $incrementId;

    /**
     * Is-virtual flag value.
     * @maps is_virtual
     * @var integer|null $isVirtual public property
     */
    public $isVirtual;

    /**
     * Order currency code.
     * @maps order_currency_code
     * @var string|null $orderCurrencyCode public property
     */
    public $orderCurrencyCode;

    /**
     * Original increment ID.
     * @maps original_increment_id
     * @var string|null $originalIncrementId public property
     */
    public $originalIncrementId;

    /**
     * Payment authorization amount.
     * @maps payment_authorization_amount
     * @var double|null $paymentAuthorizationAmount public property
     */
    public $paymentAuthorizationAmount;

    /**
     * Payment authorization expiration date.
     * @maps payment_auth_expiration
     * @var integer|null $paymentAuthExpiration public property
     */
    public $paymentAuthExpiration;

    /**
     * Protect code.
     * @maps protect_code
     * @var string|null $protectCode public property
     */
    public $protectCode;

    /**
     * Quote address ID.
     * @maps quote_address_id
     * @var integer|null $quoteAddressId public property
     */
    public $quoteAddressId;

    /**
     * Quote ID.
     * @maps quote_id
     * @var integer|null $quoteId public property
     */
    public $quoteId;

    /**
     * Relation child ID.
     * @maps relation_child_id
     * @var string|null $relationChildId public property
     */
    public $relationChildId;

    /**
     * Relation child real ID.
     * @maps relation_child_real_id
     * @var string|null $relationChildRealId public property
     */
    public $relationChildRealId;

    /**
     * Relation parent ID.
     * @maps relation_parent_id
     * @var string|null $relationParentId public property
     */
    public $relationParentId;

    /**
     * Relation parent real ID.
     * @maps relation_parent_real_id
     * @var string|null $relationParentRealId public property
     */
    public $relationParentRealId;

    /**
     * Remote IP address.
     * @maps remote_ip
     * @var string|null $remoteIp public property
     */
    public $remoteIp;

    /**
     * Shipping amount.
     * @maps shipping_amount
     * @var double|null $shippingAmount public property
     */
    public $shippingAmount;

    /**
     * Shipping canceled amount.
     * @maps shipping_canceled
     * @var double|null $shippingCanceled public property
     */
    public $shippingCanceled;

    /**
     * Shipping description.
     * @maps shipping_description
     * @var string|null $shippingDescription public property
     */
    public $shippingDescription;

    /**
     * Shipping discount amount.
     * @maps shipping_discount_amount
     * @var double|null $shippingDiscountAmount public property
     */
    public $shippingDiscountAmount;

    /**
     * Shipping discount tax compensation amount.
     * @maps shipping_discount_tax_compensation_amount
     * @var double|null $shippingDiscountTaxCompensationAmount public property
     */
    public $shippingDiscountTaxCompensationAmount;

    /**
     * Shipping including tax amount.
     * @maps shipping_incl_tax
     * @var double|null $shippingInclTax public property
     */
    public $shippingInclTax;

    /**
     * Shipping invoiced amount.
     * @maps shipping_invoiced
     * @var double|null $shippingInvoiced public property
     */
    public $shippingInvoiced;

    /**
     * Shipping refunded amount.
     * @maps shipping_refunded
     * @var double|null $shippingRefunded public property
     */
    public $shippingRefunded;

    /**
     * Shipping tax amount.
     * @maps shipping_tax_amount
     * @var double|null $shippingTaxAmount public property
     */
    public $shippingTaxAmount;

    /**
     * Shipping tax refunded amount.
     * @maps shipping_tax_refunded
     * @var double|null $shippingTaxRefunded public property
     */
    public $shippingTaxRefunded;

    /**
     * State.
     * @var string|null $state public property
     */
    public $state;

    /**
     * Status.
     * @var string|null $status public property
     */
    public $status;

    /**
     * Store currency code.
     * @maps store_currency_code
     * @var string|null $storeCurrencyCode public property
     */
    public $storeCurrencyCode;

    /**
     * Store ID.
     * @maps store_id
     * @var integer|null $storeId public property
     */
    public $storeId;

    /**
     * Store name.
     * @maps store_name
     * @var string|null $storeName public property
     */
    public $storeName;

    /**
     * Store-to-base rate.
     * @maps store_to_base_rate
     * @var double|null $storeToBaseRate public property
     */
    public $storeToBaseRate;

    /**
     * Store-to-order rate.
     * @maps store_to_order_rate
     * @var double|null $storeToOrderRate public property
     */
    public $storeToOrderRate;

    /**
     * Subtotal.
     * @var double|null $subtotal public property
     */
    public $subtotal;

    /**
     * Subtotal canceled amount.
     * @maps subtotal_canceled
     * @var double|null $subtotalCanceled public property
     */
    public $subtotalCanceled;

    /**
     * Subtotal including tax amount.
     * @maps subtotal_incl_tax
     * @var double|null $subtotalInclTax public property
     */
    public $subtotalInclTax;

    /**
     * Subtotal invoiced amount.
     * @maps subtotal_invoiced
     * @var double|null $subtotalInvoiced public property
     */
    public $subtotalInvoiced;

    /**
     * Subtotal refunded amount.
     * @maps subtotal_refunded
     * @var double|null $subtotalRefunded public property
     */
    public $subtotalRefunded;

    /**
     * Tax amount.
     * @maps tax_amount
     * @var double|null $taxAmount public property
     */
    public $taxAmount;

    /**
     * Tax canceled amount.
     * @maps tax_canceled
     * @var double|null $taxCanceled public property
     */
    public $taxCanceled;

    /**
     * Tax invoiced amount.
     * @maps tax_invoiced
     * @var double|null $taxInvoiced public property
     */
    public $taxInvoiced;

    /**
     * Tax refunded amount.
     * @maps tax_refunded
     * @var double|null $taxRefunded public property
     */
    public $taxRefunded;

    /**
     * Total canceled.
     * @maps total_canceled
     * @var double|null $totalCanceled public property
     */
    public $totalCanceled;

    /**
     * Total due.
     * @maps total_due
     * @var double|null $totalDue public property
     */
    public $totalDue;

    /**
     * Total invoiced amount.
     * @maps total_invoiced
     * @var double|null $totalInvoiced public property
     */
    public $totalInvoiced;

    /**
     * Total item count.
     * @maps total_item_count
     * @var integer|null $totalItemCount public property
     */
    public $totalItemCount;

    /**
     * Total offline refunded amount.
     * @maps total_offline_refunded
     * @var double|null $totalOfflineRefunded public property
     */
    public $totalOfflineRefunded;

    /**
     * Total online refunded amount.
     * @maps total_online_refunded
     * @var double|null $totalOnlineRefunded public property
     */
    public $totalOnlineRefunded;

    /**
     * Total paid.
     * @maps total_paid
     * @var double|null $totalPaid public property
     */
    public $totalPaid;

    /**
     * Total quantity ordered.
     * @maps total_qty_ordered
     * @var double|null $totalQtyOrdered public property
     */
    public $totalQtyOrdered;

    /**
     * Total amount refunded.
     * @maps total_refunded
     * @var double|null $totalRefunded public property
     */
    public $totalRefunded;

    /**
     * Updated-at timestamp.
     * @maps updated_at
     * @var string|null $updatedAt public property
     */
    public $updatedAt;

    /**
     * Weight.
     * @var double|null $weight public property
     */
    public $weight;

    /**
     * X-Forwarded-For field value.
     * @maps x_forwarded_for
     * @var string|null $xForwardedFor public property
     */
    public $xForwardedFor;

    /**
     * Order address interface. An order is a document that a web store issues to a customer. Magento
     * generates a sales order that lists the product items, billing and shipping addresses, and shipping
     * and payment methods. A corresponding external document, known as a purchase order, is emailed to the
     * customer.
     * @maps billing_address
     * @var \MagentoCommunityLib\Models\SalesDataOrderAddressInterface|null $billingAddress public property
     */
    public $billingAddress;

    /**
     * Order payment interface. An order is a document that a web store issues to a customer. Magento
     * generates a sales order that lists the product items, billing and shipping addresses, and shipping
     * and payment methods. A corresponding external document, known as a purchase order, is emailed to the
     * customer.
     * @var \MagentoCommunityLib\Models\SalesDataOrderPaymentInterface|null $payment public property
     */
    public $payment;

    /**
     * Array of status histories.
     * @maps status_histories
     * @var \MagentoCommunityLib\Models\SalesDataOrderStatusHistoryInterface[]|null $statusHistories public property
     */
    public $statusHistories;

    /**
     * ExtensionInterface class for @see \Magento\Sales\Api\Data\OrderInterface
     * @maps extension_attributes
     * @var \MagentoCommunityLib\Models\SalesDataOrderExtensionInterface|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param double                           $baseGrandTotal                          Initialization value for $this-
     *                                                                                    >baseGrandTotal
     * @param string                           $customerEmail                           Initialization value for $this-
     *                                                                                    >customerEmail
     * @param double                           $grandTotal                              Initialization value for $this-
     *                                                                                    >grandTotal
     * @param array                            $items                                   Initialization value for $this-
     *                                                                                    >items
     * @param double                           $adjustmentNegative                      Initialization value for $this-
     *                                                                                    >adjustmentNegative
     * @param double                           $adjustmentPositive                      Initialization value for $this-
     *                                                                                    >adjustmentPositive
     * @param string                           $appliedRuleIds                          Initialization value for $this-
     *                                                                                    >appliedRuleIds
     * @param double                           $baseAdjustmentNegative                  Initialization value for $this-
     *                                                                                    >baseAdjustmentNegative
     * @param double                           $baseAdjustmentPositive                  Initialization value for $this-
     *                                                                                    >baseAdjustmentPositive
     * @param string                           $baseCurrencyCode                        Initialization value for $this-
     *                                                                                    >baseCurrencyCode
     * @param double                           $baseDiscountAmount                      Initialization value for $this-
     *                                                                                    >baseDiscountAmount
     * @param double                           $baseDiscountCanceled                    Initialization value for $this-
     *                                                                                    >baseDiscountCanceled
     * @param double                           $baseDiscountInvoiced                    Initialization value for $this-
     *                                                                                    >baseDiscountInvoiced
     * @param double                           $baseDiscountRefunded                    Initialization value for $this-
     *                                                                                    >baseDiscountRefunded
     * @param double                           $baseDiscountTaxCompensationAmount       Initialization value for $this-
     *                                                                                    >baseDiscountTaxCompensationAm
     *                                                                                    ount
     * @param double                           $baseDiscountTaxCompensationInvoiced     Initialization value for $this-
     *                                                                                    >baseDiscountTaxCompensationIn
     *                                                                                    voiced
     * @param double                           $baseDiscountTaxCompensationRefunded     Initialization value for $this-
     *                                                                                    >baseDiscountTaxCompensationRe
     *                                                                                    funded
     * @param double                           $baseShippingAmount                      Initialization value for $this-
     *                                                                                    >baseShippingAmount
     * @param double                           $baseShippingCanceled                    Initialization value for $this-
     *                                                                                    >baseShippingCanceled
     * @param double                           $baseShippingDiscountAmount              Initialization value for $this-
     *                                                                                    >baseShippingDiscountAmount
     * @param double                           $baseShippingDiscountTaxCompensationAmnt Initialization value for $this-
     *                                                                                    >baseShippingDiscountTaxCompen
     *                                                                                    sationAmnt
     * @param double                           $baseShippingInclTax                     Initialization value for $this-
     *                                                                                    >baseShippingInclTax
     * @param double                           $baseShippingInvoiced                    Initialization value for $this-
     *                                                                                    >baseShippingInvoiced
     * @param double                           $baseShippingRefunded                    Initialization value for $this-
     *                                                                                    >baseShippingRefunded
     * @param double                           $baseShippingTaxAmount                   Initialization value for $this-
     *                                                                                    >baseShippingTaxAmount
     * @param double                           $baseShippingTaxRefunded                 Initialization value for $this-
     *                                                                                    >baseShippingTaxRefunded
     * @param double                           $baseSubtotal                            Initialization value for $this-
     *                                                                                    >baseSubtotal
     * @param double                           $baseSubtotalCanceled                    Initialization value for $this-
     *                                                                                    >baseSubtotalCanceled
     * @param double                           $baseSubtotalInclTax                     Initialization value for $this-
     *                                                                                    >baseSubtotalInclTax
     * @param double                           $baseSubtotalInvoiced                    Initialization value for $this-
     *                                                                                    >baseSubtotalInvoiced
     * @param double                           $baseSubtotalRefunded                    Initialization value for $this-
     *                                                                                    >baseSubtotalRefunded
     * @param double                           $baseTaxAmount                           Initialization value for $this-
     *                                                                                    >baseTaxAmount
     * @param double                           $baseTaxCanceled                         Initialization value for $this-
     *                                                                                    >baseTaxCanceled
     * @param double                           $baseTaxInvoiced                         Initialization value for $this-
     *                                                                                    >baseTaxInvoiced
     * @param double                           $baseTaxRefunded                         Initialization value for $this-
     *                                                                                    >baseTaxRefunded
     * @param double                           $baseTotalCanceled                       Initialization value for $this-
     *                                                                                    >baseTotalCanceled
     * @param double                           $baseTotalDue                            Initialization value for $this-
     *                                                                                    >baseTotalDue
     * @param double                           $baseTotalInvoiced                       Initialization value for $this-
     *                                                                                    >baseTotalInvoiced
     * @param double                           $baseTotalInvoicedCost                   Initialization value for $this-
     *                                                                                    >baseTotalInvoicedCost
     * @param double                           $baseTotalOfflineRefunded                Initialization value for $this-
     *                                                                                    >baseTotalOfflineRefunded
     * @param double                           $baseTotalOnlineRefunded                 Initialization value for $this-
     *                                                                                    >baseTotalOnlineRefunded
     * @param double                           $baseTotalPaid                           Initialization value for $this-
     *                                                                                    >baseTotalPaid
     * @param double                           $baseTotalQtyOrdered                     Initialization value for $this-
     *                                                                                    >baseTotalQtyOrdered
     * @param double                           $baseTotalRefunded                       Initialization value for $this-
     *                                                                                    >baseTotalRefunded
     * @param double                           $baseToGlobalRate                        Initialization value for $this-
     *                                                                                    >baseToGlobalRate
     * @param double                           $baseToOrderRate                         Initialization value for $this-
     *                                                                                    >baseToOrderRate
     * @param integer                          $billingAddressId                        Initialization value for $this-
     *                                                                                    >billingAddressId
     * @param integer                          $canShipPartially                        Initialization value for $this-
     *                                                                                    >canShipPartially
     * @param integer                          $canShipPartiallyItem                    Initialization value for $this-
     *                                                                                    >canShipPartiallyItem
     * @param string                           $couponCode                              Initialization value for $this-
     *                                                                                    >couponCode
     * @param string                           $createdAt                               Initialization value for $this-
     *                                                                                    >createdAt
     * @param string                           $customerDob                             Initialization value for $this-
     *                                                                                    >customerDob
     * @param string                           $customerFirstname                       Initialization value for $this-
     *                                                                                    >customerFirstname
     * @param integer                          $customerGender                          Initialization value for $this-
     *                                                                                    >customerGender
     * @param integer                          $customerGroupId                         Initialization value for $this-
     *                                                                                    >customerGroupId
     * @param integer                          $customerId                              Initialization value for $this-
     *                                                                                    >customerId
     * @param integer                          $customerIsGuest                         Initialization value for $this-
     *                                                                                    >customerIsGuest
     * @param string                           $customerLastname                        Initialization value for $this-
     *                                                                                    >customerLastname
     * @param string                           $customerMiddlename                      Initialization value for $this-
     *                                                                                    >customerMiddlename
     * @param string                           $customerNote                            Initialization value for $this-
     *                                                                                    >customerNote
     * @param integer                          $customerNoteNotify                      Initialization value for $this-
     *                                                                                    >customerNoteNotify
     * @param string                           $customerPrefix                          Initialization value for $this-
     *                                                                                    >customerPrefix
     * @param string                           $customerSuffix                          Initialization value for $this-
     *                                                                                    >customerSuffix
     * @param string                           $customerTaxvat                          Initialization value for $this-
     *                                                                                    >customerTaxvat
     * @param double                           $discountAmount                          Initialization value for $this-
     *                                                                                    >discountAmount
     * @param double                           $discountCanceled                        Initialization value for $this-
     *                                                                                    >discountCanceled
     * @param string                           $discountDescription                     Initialization value for $this-
     *                                                                                    >discountDescription
     * @param double                           $discountInvoiced                        Initialization value for $this-
     *                                                                                    >discountInvoiced
     * @param double                           $discountRefunded                        Initialization value for $this-
     *                                                                                    >discountRefunded
     * @param integer                          $editIncrement                           Initialization value for $this-
     *                                                                                    >editIncrement
     * @param integer                          $emailSent                               Initialization value for $this-
     *                                                                                    >emailSent
     * @param integer                          $entityId                                Initialization value for $this-
     *                                                                                    >entityId
     * @param string                           $extCustomerId                           Initialization value for $this-
     *                                                                                    >extCustomerId
     * @param string                           $extOrderId                              Initialization value for $this-
     *                                                                                    >extOrderId
     * @param integer                          $forcedShipmentWithInvoice               Initialization value for $this-
     *                                                                                    >forcedShipmentWithInvoice
     * @param string                           $globalCurrencyCode                      Initialization value for $this-
     *                                                                                    >globalCurrencyCode
     * @param double                           $discountTaxCompensationAmount           Initialization value for $this-
     *                                                                                    >discountTaxCompensationAmount
     * @param double                           $discountTaxCompensationInvoiced         Initialization value for $this-
     *                                                                                    >discountTaxCompensationInvoic
     *                                                                                    ed
     * @param double                           $discountTaxCompensationRefunded         Initialization value for $this-
     *                                                                                    >discountTaxCompensationRefund
     *                                                                                    ed
     * @param string                           $holdBeforeState                         Initialization value for $this-
     *                                                                                    >holdBeforeState
     * @param string                           $holdBeforeStatus                        Initialization value for $this-
     *                                                                                    >holdBeforeStatus
     * @param string                           $incrementId                             Initialization value for $this-
     *                                                                                    >incrementId
     * @param integer                          $isVirtual                               Initialization value for $this-
     *                                                                                    >isVirtual
     * @param string                           $orderCurrencyCode                       Initialization value for $this-
     *                                                                                    >orderCurrencyCode
     * @param string                           $originalIncrementId                     Initialization value for $this-
     *                                                                                    >originalIncrementId
     * @param double                           $paymentAuthorizationAmount              Initialization value for $this-
     *                                                                                    >paymentAuthorizationAmount
     * @param integer                          $paymentAuthExpiration                   Initialization value for $this-
     *                                                                                    >paymentAuthExpiration
     * @param string                           $protectCode                             Initialization value for $this-
     *                                                                                    >protectCode
     * @param integer                          $quoteAddressId                          Initialization value for $this-
     *                                                                                    >quoteAddressId
     * @param integer                          $quoteId                                 Initialization value for $this-
     *                                                                                    >quoteId
     * @param string                           $relationChildId                         Initialization value for $this-
     *                                                                                    >relationChildId
     * @param string                           $relationChildRealId                     Initialization value for $this-
     *                                                                                    >relationChildRealId
     * @param string                           $relationParentId                        Initialization value for $this-
     *                                                                                    >relationParentId
     * @param string                           $relationParentRealId                    Initialization value for $this-
     *                                                                                    >relationParentRealId
     * @param string                           $remoteIp                                Initialization value for $this-
     *                                                                                    >remoteIp
     * @param double                           $shippingAmount                          Initialization value for $this-
     *                                                                                    >shippingAmount
     * @param double                           $shippingCanceled                        Initialization value for $this-
     *                                                                                    >shippingCanceled
     * @param string                           $shippingDescription                     Initialization value for $this-
     *                                                                                    >shippingDescription
     * @param double                           $shippingDiscountAmount                  Initialization value for $this-
     *                                                                                    >shippingDiscountAmount
     * @param double                           $shippingDiscountTaxCompensationAmount   Initialization value for $this-
     *                                                                                    >shippingDiscountTaxCompensati
     *                                                                                    onAmount
     * @param double                           $shippingInclTax                         Initialization value for $this-
     *                                                                                    >shippingInclTax
     * @param double                           $shippingInvoiced                        Initialization value for $this-
     *                                                                                    >shippingInvoiced
     * @param double                           $shippingRefunded                        Initialization value for $this-
     *                                                                                    >shippingRefunded
     * @param double                           $shippingTaxAmount                       Initialization value for $this-
     *                                                                                    >shippingTaxAmount
     * @param double                           $shippingTaxRefunded                     Initialization value for $this-
     *                                                                                    >shippingTaxRefunded
     * @param string                           $state                                   Initialization value for $this-
     *                                                                                    >state
     * @param string                           $status                                  Initialization value for $this-
     *                                                                                    >status
     * @param string                           $storeCurrencyCode                       Initialization value for $this-
     *                                                                                    >storeCurrencyCode
     * @param integer                          $storeId                                 Initialization value for $this-
     *                                                                                    >storeId
     * @param string                           $storeName                               Initialization value for $this-
     *                                                                                    >storeName
     * @param double                           $storeToBaseRate                         Initialization value for $this-
     *                                                                                    >storeToBaseRate
     * @param double                           $storeToOrderRate                        Initialization value for $this-
     *                                                                                    >storeToOrderRate
     * @param double                           $subtotal                                Initialization value for $this-
     *                                                                                    >subtotal
     * @param double                           $subtotalCanceled                        Initialization value for $this-
     *                                                                                    >subtotalCanceled
     * @param double                           $subtotalInclTax                         Initialization value for $this-
     *                                                                                    >subtotalInclTax
     * @param double                           $subtotalInvoiced                        Initialization value for $this-
     *                                                                                    >subtotalInvoiced
     * @param double                           $subtotalRefunded                        Initialization value for $this-
     *                                                                                    >subtotalRefunded
     * @param double                           $taxAmount                               Initialization value for $this-
     *                                                                                    >taxAmount
     * @param double                           $taxCanceled                             Initialization value for $this-
     *                                                                                    >taxCanceled
     * @param double                           $taxInvoiced                             Initialization value for $this-
     *                                                                                    >taxInvoiced
     * @param double                           $taxRefunded                             Initialization value for $this-
     *                                                                                    >taxRefunded
     * @param double                           $totalCanceled                           Initialization value for $this-
     *                                                                                    >totalCanceled
     * @param double                           $totalDue                                Initialization value for $this-
     *                                                                                    >totalDue
     * @param double                           $totalInvoiced                           Initialization value for $this-
     *                                                                                    >totalInvoiced
     * @param integer                          $totalItemCount                          Initialization value for $this-
     *                                                                                    >totalItemCount
     * @param double                           $totalOfflineRefunded                    Initialization value for $this-
     *                                                                                    >totalOfflineRefunded
     * @param double                           $totalOnlineRefunded                     Initialization value for $this-
     *                                                                                    >totalOnlineRefunded
     * @param double                           $totalPaid                               Initialization value for $this-
     *                                                                                    >totalPaid
     * @param double                           $totalQtyOrdered                         Initialization value for $this-
     *                                                                                    >totalQtyOrdered
     * @param double                           $totalRefunded                           Initialization value for $this-
     *                                                                                    >totalRefunded
     * @param string                           $updatedAt                               Initialization value for $this-
     *                                                                                    >updatedAt
     * @param double                           $weight                                  Initialization value for $this-
     *                                                                                    >weight
     * @param string                           $xForwardedFor                           Initialization value for $this-
     *                                                                                    >xForwardedFor
     * @param SalesDataOrderAddressInterface   $billingAddress                          Initialization value for $this-
     *                                                                                    >billingAddress
     * @param SalesDataOrderPaymentInterface   $payment                                 Initialization value for $this-
     *                                                                                    >payment
     * @param array                            $statusHistories                         Initialization value for $this-
     *                                                                                    >statusHistories
     * @param SalesDataOrderExtensionInterface $extensionAttributes                     Initialization value for $this-
     *                                                                                    >extensionAttributes
     */
    public function __construct()
    {
        if (137 == func_num_args()) {
            $this->baseGrandTotal                          = func_get_arg(0);
            $this->customerEmail                           = func_get_arg(1);
            $this->grandTotal                              = func_get_arg(2);
            $this->items                                   = func_get_arg(3);
            $this->adjustmentNegative                      = func_get_arg(4);
            $this->adjustmentPositive                      = func_get_arg(5);
            $this->appliedRuleIds                          = func_get_arg(6);
            $this->baseAdjustmentNegative                  = func_get_arg(7);
            $this->baseAdjustmentPositive                  = func_get_arg(8);
            $this->baseCurrencyCode                        = func_get_arg(9);
            $this->baseDiscountAmount                      = func_get_arg(10);
            $this->baseDiscountCanceled                    = func_get_arg(11);
            $this->baseDiscountInvoiced                    = func_get_arg(12);
            $this->baseDiscountRefunded                    = func_get_arg(13);
            $this->baseDiscountTaxCompensationAmount       = func_get_arg(14);
            $this->baseDiscountTaxCompensationInvoiced     = func_get_arg(15);
            $this->baseDiscountTaxCompensationRefunded     = func_get_arg(16);
            $this->baseShippingAmount                      = func_get_arg(17);
            $this->baseShippingCanceled                    = func_get_arg(18);
            $this->baseShippingDiscountAmount              = func_get_arg(19);
            $this->baseShippingDiscountTaxCompensationAmnt = func_get_arg(20);
            $this->baseShippingInclTax                     = func_get_arg(21);
            $this->baseShippingInvoiced                    = func_get_arg(22);
            $this->baseShippingRefunded                    = func_get_arg(23);
            $this->baseShippingTaxAmount                   = func_get_arg(24);
            $this->baseShippingTaxRefunded                 = func_get_arg(25);
            $this->baseSubtotal                            = func_get_arg(26);
            $this->baseSubtotalCanceled                    = func_get_arg(27);
            $this->baseSubtotalInclTax                     = func_get_arg(28);
            $this->baseSubtotalInvoiced                    = func_get_arg(29);
            $this->baseSubtotalRefunded                    = func_get_arg(30);
            $this->baseTaxAmount                           = func_get_arg(31);
            $this->baseTaxCanceled                         = func_get_arg(32);
            $this->baseTaxInvoiced                         = func_get_arg(33);
            $this->baseTaxRefunded                         = func_get_arg(34);
            $this->baseTotalCanceled                       = func_get_arg(35);
            $this->baseTotalDue                            = func_get_arg(36);
            $this->baseTotalInvoiced                       = func_get_arg(37);
            $this->baseTotalInvoicedCost                   = func_get_arg(38);
            $this->baseTotalOfflineRefunded                = func_get_arg(39);
            $this->baseTotalOnlineRefunded                 = func_get_arg(40);
            $this->baseTotalPaid                           = func_get_arg(41);
            $this->baseTotalQtyOrdered                     = func_get_arg(42);
            $this->baseTotalRefunded                       = func_get_arg(43);
            $this->baseToGlobalRate                        = func_get_arg(44);
            $this->baseToOrderRate                         = func_get_arg(45);
            $this->billingAddressId                        = func_get_arg(46);
            $this->canShipPartially                        = func_get_arg(47);
            $this->canShipPartiallyItem                    = func_get_arg(48);
            $this->couponCode                              = func_get_arg(49);
            $this->createdAt                               = func_get_arg(50);
            $this->customerDob                             = func_get_arg(51);
            $this->customerFirstname                       = func_get_arg(52);
            $this->customerGender                          = func_get_arg(53);
            $this->customerGroupId                         = func_get_arg(54);
            $this->customerId                              = func_get_arg(55);
            $this->customerIsGuest                         = func_get_arg(56);
            $this->customerLastname                        = func_get_arg(57);
            $this->customerMiddlename                      = func_get_arg(58);
            $this->customerNote                            = func_get_arg(59);
            $this->customerNoteNotify                      = func_get_arg(60);
            $this->customerPrefix                          = func_get_arg(61);
            $this->customerSuffix                          = func_get_arg(62);
            $this->customerTaxvat                          = func_get_arg(63);
            $this->discountAmount                          = func_get_arg(64);
            $this->discountCanceled                        = func_get_arg(65);
            $this->discountDescription                     = func_get_arg(66);
            $this->discountInvoiced                        = func_get_arg(67);
            $this->discountRefunded                        = func_get_arg(68);
            $this->editIncrement                           = func_get_arg(69);
            $this->emailSent                               = func_get_arg(70);
            $this->entityId                                = func_get_arg(71);
            $this->extCustomerId                           = func_get_arg(72);
            $this->extOrderId                              = func_get_arg(73);
            $this->forcedShipmentWithInvoice               = func_get_arg(74);
            $this->globalCurrencyCode                      = func_get_arg(75);
            $this->discountTaxCompensationAmount           = func_get_arg(76);
            $this->discountTaxCompensationInvoiced         = func_get_arg(77);
            $this->discountTaxCompensationRefunded         = func_get_arg(78);
            $this->holdBeforeState                         = func_get_arg(79);
            $this->holdBeforeStatus                        = func_get_arg(80);
            $this->incrementId                             = func_get_arg(81);
            $this->isVirtual                               = func_get_arg(82);
            $this->orderCurrencyCode                       = func_get_arg(83);
            $this->originalIncrementId                     = func_get_arg(84);
            $this->paymentAuthorizationAmount              = func_get_arg(85);
            $this->paymentAuthExpiration                   = func_get_arg(86);
            $this->protectCode                             = func_get_arg(87);
            $this->quoteAddressId                          = func_get_arg(88);
            $this->quoteId                                 = func_get_arg(89);
            $this->relationChildId                         = func_get_arg(90);
            $this->relationChildRealId                     = func_get_arg(91);
            $this->relationParentId                        = func_get_arg(92);
            $this->relationParentRealId                    = func_get_arg(93);
            $this->remoteIp                                = func_get_arg(94);
            $this->shippingAmount                          = func_get_arg(95);
            $this->shippingCanceled                        = func_get_arg(96);
            $this->shippingDescription                     = func_get_arg(97);
            $this->shippingDiscountAmount                  = func_get_arg(98);
            $this->shippingDiscountTaxCompensationAmount   = func_get_arg(99);
            $this->shippingInclTax                         = func_get_arg(100);
            $this->shippingInvoiced                        = func_get_arg(101);
            $this->shippingRefunded                        = func_get_arg(102);
            $this->shippingTaxAmount                       = func_get_arg(103);
            $this->shippingTaxRefunded                     = func_get_arg(104);
            $this->state                                   = func_get_arg(105);
            $this->status                                  = func_get_arg(106);
            $this->storeCurrencyCode                       = func_get_arg(107);
            $this->storeId                                 = func_get_arg(108);
            $this->storeName                               = func_get_arg(109);
            $this->storeToBaseRate                         = func_get_arg(110);
            $this->storeToOrderRate                        = func_get_arg(111);
            $this->subtotal                                = func_get_arg(112);
            $this->subtotalCanceled                        = func_get_arg(113);
            $this->subtotalInclTax                         = func_get_arg(114);
            $this->subtotalInvoiced                        = func_get_arg(115);
            $this->subtotalRefunded                        = func_get_arg(116);
            $this->taxAmount                               = func_get_arg(117);
            $this->taxCanceled                             = func_get_arg(118);
            $this->taxInvoiced                             = func_get_arg(119);
            $this->taxRefunded                             = func_get_arg(120);
            $this->totalCanceled                           = func_get_arg(121);
            $this->totalDue                                = func_get_arg(122);
            $this->totalInvoiced                           = func_get_arg(123);
            $this->totalItemCount                          = func_get_arg(124);
            $this->totalOfflineRefunded                    = func_get_arg(125);
            $this->totalOnlineRefunded                     = func_get_arg(126);
            $this->totalPaid                               = func_get_arg(127);
            $this->totalQtyOrdered                         = func_get_arg(128);
            $this->totalRefunded                           = func_get_arg(129);
            $this->updatedAt                               = func_get_arg(130);
            $this->weight                                  = func_get_arg(131);
            $this->xForwardedFor                           = func_get_arg(132);
            $this->billingAddress                          = func_get_arg(133);
            $this->payment                                 = func_get_arg(134);
            $this->statusHistories                         = func_get_arg(135);
            $this->extensionAttributes                     = func_get_arg(136);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['base_grand_total']                             = $this->baseGrandTotal;
        $json['customer_email']                               = $this->customerEmail;
        $json['grand_total']                                  = $this->grandTotal;
        $json['items']                                        = $this->items;
        $json['adjustment_negative']                          = $this->adjustmentNegative;
        $json['adjustment_positive']                          = $this->adjustmentPositive;
        $json['applied_rule_ids']                             = $this->appliedRuleIds;
        $json['base_adjustment_negative']                     = $this->baseAdjustmentNegative;
        $json['base_adjustment_positive']                     = $this->baseAdjustmentPositive;
        $json['base_currency_code']                           = $this->baseCurrencyCode;
        $json['base_discount_amount']                         = $this->baseDiscountAmount;
        $json['base_discount_canceled']                       = $this->baseDiscountCanceled;
        $json['base_discount_invoiced']                       = $this->baseDiscountInvoiced;
        $json['base_discount_refunded']                       = $this->baseDiscountRefunded;
        $json['base_discount_tax_compensation_amount']        = $this->baseDiscountTaxCompensationAmount;
        $json['base_discount_tax_compensation_invoiced']      = $this->baseDiscountTaxCompensationInvoiced;
        $json['base_discount_tax_compensation_refunded']      = $this->baseDiscountTaxCompensationRefunded;
        $json['base_shipping_amount']                         = $this->baseShippingAmount;
        $json['base_shipping_canceled']                       = $this->baseShippingCanceled;
        $json['base_shipping_discount_amount']                = $this->baseShippingDiscountAmount;
        $json['base_shipping_discount_tax_compensation_amnt'] = $this->baseShippingDiscountTaxCompensationAmnt;
        $json['base_shipping_incl_tax']                       = $this->baseShippingInclTax;
        $json['base_shipping_invoiced']                       = $this->baseShippingInvoiced;
        $json['base_shipping_refunded']                       = $this->baseShippingRefunded;
        $json['base_shipping_tax_amount']                     = $this->baseShippingTaxAmount;
        $json['base_shipping_tax_refunded']                   = $this->baseShippingTaxRefunded;
        $json['base_subtotal']                                = $this->baseSubtotal;
        $json['base_subtotal_canceled']                       = $this->baseSubtotalCanceled;
        $json['base_subtotal_incl_tax']                       = $this->baseSubtotalInclTax;
        $json['base_subtotal_invoiced']                       = $this->baseSubtotalInvoiced;
        $json['base_subtotal_refunded']                       = $this->baseSubtotalRefunded;
        $json['base_tax_amount']                              = $this->baseTaxAmount;
        $json['base_tax_canceled']                            = $this->baseTaxCanceled;
        $json['base_tax_invoiced']                            = $this->baseTaxInvoiced;
        $json['base_tax_refunded']                            = $this->baseTaxRefunded;
        $json['base_total_canceled']                          = $this->baseTotalCanceled;
        $json['base_total_due']                               = $this->baseTotalDue;
        $json['base_total_invoiced']                          = $this->baseTotalInvoiced;
        $json['base_total_invoiced_cost']                     = $this->baseTotalInvoicedCost;
        $json['base_total_offline_refunded']                  = $this->baseTotalOfflineRefunded;
        $json['base_total_online_refunded']                   = $this->baseTotalOnlineRefunded;
        $json['base_total_paid']                              = $this->baseTotalPaid;
        $json['base_total_qty_ordered']                       = $this->baseTotalQtyOrdered;
        $json['base_total_refunded']                          = $this->baseTotalRefunded;
        $json['base_to_global_rate']                          = $this->baseToGlobalRate;
        $json['base_to_order_rate']                           = $this->baseToOrderRate;
        $json['billing_address_id']                           = $this->billingAddressId;
        $json['can_ship_partially']                           = $this->canShipPartially;
        $json['can_ship_partially_item']                      = $this->canShipPartiallyItem;
        $json['coupon_code']                                  = $this->couponCode;
        $json['created_at']                                   = $this->createdAt;
        $json['customer_dob']                                 = $this->customerDob;
        $json['customer_firstname']                           = $this->customerFirstname;
        $json['customer_gender']                              = $this->customerGender;
        $json['customer_group_id']                            = $this->customerGroupId;
        $json['customer_id']                                  = $this->customerId;
        $json['customer_is_guest']                            = $this->customerIsGuest;
        $json['customer_lastname']                            = $this->customerLastname;
        $json['customer_middlename']                          = $this->customerMiddlename;
        $json['customer_note']                                = $this->customerNote;
        $json['customer_note_notify']                         = $this->customerNoteNotify;
        $json['customer_prefix']                              = $this->customerPrefix;
        $json['customer_suffix']                              = $this->customerSuffix;
        $json['customer_taxvat']                              = $this->customerTaxvat;
        $json['discount_amount']                              = $this->discountAmount;
        $json['discount_canceled']                            = $this->discountCanceled;
        $json['discount_description']                         = $this->discountDescription;
        $json['discount_invoiced']                            = $this->discountInvoiced;
        $json['discount_refunded']                            = $this->discountRefunded;
        $json['edit_increment']                               = $this->editIncrement;
        $json['email_sent']                                   = $this->emailSent;
        $json['entity_id']                                    = $this->entityId;
        $json['ext_customer_id']                              = $this->extCustomerId;
        $json['ext_order_id']                                 = $this->extOrderId;
        $json['forced_shipment_with_invoice']                 = $this->forcedShipmentWithInvoice;
        $json['global_currency_code']                         = $this->globalCurrencyCode;
        $json['discount_tax_compensation_amount']             = $this->discountTaxCompensationAmount;
        $json['discount_tax_compensation_invoiced']           = $this->discountTaxCompensationInvoiced;
        $json['discount_tax_compensation_refunded']           = $this->discountTaxCompensationRefunded;
        $json['hold_before_state']                            = $this->holdBeforeState;
        $json['hold_before_status']                           = $this->holdBeforeStatus;
        $json['increment_id']                                 = $this->incrementId;
        $json['is_virtual']                                   = $this->isVirtual;
        $json['order_currency_code']                          = $this->orderCurrencyCode;
        $json['original_increment_id']                        = $this->originalIncrementId;
        $json['payment_authorization_amount']                 = $this->paymentAuthorizationAmount;
        $json['payment_auth_expiration']                      = $this->paymentAuthExpiration;
        $json['protect_code']                                 = $this->protectCode;
        $json['quote_address_id']                             = $this->quoteAddressId;
        $json['quote_id']                                     = $this->quoteId;
        $json['relation_child_id']                            = $this->relationChildId;
        $json['relation_child_real_id']                       = $this->relationChildRealId;
        $json['relation_parent_id']                           = $this->relationParentId;
        $json['relation_parent_real_id']                      = $this->relationParentRealId;
        $json['remote_ip']                                    = $this->remoteIp;
        $json['shipping_amount']                              = $this->shippingAmount;
        $json['shipping_canceled']                            = $this->shippingCanceled;
        $json['shipping_description']                         = $this->shippingDescription;
        $json['shipping_discount_amount']                     = $this->shippingDiscountAmount;
        $json['shipping_discount_tax_compensation_amount']    = $this->shippingDiscountTaxCompensationAmount;
        $json['shipping_incl_tax']                            = $this->shippingInclTax;
        $json['shipping_invoiced']                            = $this->shippingInvoiced;
        $json['shipping_refunded']                            = $this->shippingRefunded;
        $json['shipping_tax_amount']                          = $this->shippingTaxAmount;
        $json['shipping_tax_refunded']                        = $this->shippingTaxRefunded;
        $json['state']                                        = $this->state;
        $json['status']                                       = $this->status;
        $json['store_currency_code']                          = $this->storeCurrencyCode;
        $json['store_id']                                     = $this->storeId;
        $json['store_name']                                   = $this->storeName;
        $json['store_to_base_rate']                           = $this->storeToBaseRate;
        $json['store_to_order_rate']                          = $this->storeToOrderRate;
        $json['subtotal']                                     = $this->subtotal;
        $json['subtotal_canceled']                            = $this->subtotalCanceled;
        $json['subtotal_incl_tax']                            = $this->subtotalInclTax;
        $json['subtotal_invoiced']                            = $this->subtotalInvoiced;
        $json['subtotal_refunded']                            = $this->subtotalRefunded;
        $json['tax_amount']                                   = $this->taxAmount;
        $json['tax_canceled']                                 = $this->taxCanceled;
        $json['tax_invoiced']                                 = $this->taxInvoiced;
        $json['tax_refunded']                                 = $this->taxRefunded;
        $json['total_canceled']                               = $this->totalCanceled;
        $json['total_due']                                    = $this->totalDue;
        $json['total_invoiced']                               = $this->totalInvoiced;
        $json['total_item_count']                             = $this->totalItemCount;
        $json['total_offline_refunded']                       = $this->totalOfflineRefunded;
        $json['total_online_refunded']                        = $this->totalOnlineRefunded;
        $json['total_paid']                                   = $this->totalPaid;
        $json['total_qty_ordered']                            = $this->totalQtyOrdered;
        $json['total_refunded']                               = $this->totalRefunded;
        $json['updated_at']                                   = $this->updatedAt;
        $json['weight']                                       = $this->weight;
        $json['x_forwarded_for']                              = $this->xForwardedFor;
        $json['billing_address']                              = $this->billingAddress;
        $json['payment']                                      = $this->payment;
        $json['status_histories']                             = $this->statusHistories;
        $json['extension_attributes']                         = $this->extensionAttributes;

        return $json;
    }
}
