<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SalesDataOrderExtensionInterface implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @maps shipping_assignments
     * @var \MagentoCommunityLib\Models\SalesDataShippingAssignmentInterface[]|null $shippingAssignments public property
     */
    public $shippingAssignments;

    /**
     * Interface MessageInterface
     * @maps gift_message
     * @var \MagentoCommunityLib\Models\GiftMessageDataMessageInterface|null $giftMessage public property
     */
    public $giftMessage;

    /**
     * @todo Write general description for this property
     * @maps amazon_order_reference_id
     * @var string|null $amazonOrderReferenceId public property
     */
    public $amazonOrderReferenceId;

    /**
     * @todo Write general description for this property
     * @maps applied_taxes
     * @var \MagentoCommunityLib\Models\TaxDataOrderTaxDetailsAppliedTaxInterface[]|null $appliedTaxes public property
     */
    public $appliedTaxes;

    /**
     * @todo Write general description for this property
     * @maps item_applied_taxes
     * @var \MagentoCommunityLib\Models\TaxDataOrderTaxDetailsItemInterface[]|null $itemAppliedTaxes public property
     */
    public $itemAppliedTaxes;

    /**
     * @todo Write general description for this property
     * @maps converting_from_quote
     * @var bool|null $convertingFromQuote public property
     */
    public $convertingFromQuote;

    /**
     * Constructor to set initial or default values of member properties
     * @param array                           $shippingAssignments    Initialization value for $this-
     *                                                                  >shippingAssignments
     * @param GiftMessageDataMessageInterface $giftMessage            Initialization value for $this->giftMessage
     * @param string                          $amazonOrderReferenceId Initialization value for $this-
     *                                                                  >amazonOrderReferenceId
     * @param array                           $appliedTaxes           Initialization value for $this->appliedTaxes
     * @param array                           $itemAppliedTaxes       Initialization value for $this-
     *                                                                  >itemAppliedTaxes
     * @param bool                            $convertingFromQuote    Initialization value for $this-
     *                                                                  >convertingFromQuote
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->shippingAssignments    = func_get_arg(0);
            $this->giftMessage            = func_get_arg(1);
            $this->amazonOrderReferenceId = func_get_arg(2);
            $this->appliedTaxes           = func_get_arg(3);
            $this->itemAppliedTaxes       = func_get_arg(4);
            $this->convertingFromQuote    = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['shipping_assignments']      = $this->shippingAssignments;
        $json['gift_message']              = $this->giftMessage;
        $json['amazon_order_reference_id'] = $this->amazonOrderReferenceId;
        $json['applied_taxes']             = $this->appliedTaxes;
        $json['item_applied_taxes']        = $this->itemAppliedTaxes;
        $json['converting_from_quote']     = $this->convertingFromQuote;

        return $json;
    }
}
