<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SalesRuleCouponManagementV1GeneratePostBody implements JsonSerializable
{
    /**
     * CouponGenerationSpecInterface
     * @required
     * @var \MagentoCommunityLib\Models\SalesRuleDataCouponGenerationSpecInterface $couponSpec public property
     */
    public $couponSpec;

    /**
     * Constructor to set initial or default values of member properties
     * @param SalesRuleDataCouponGenerationSpecInterface $couponSpec Initialization value for $this->couponSpec
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->couponSpec = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['couponSpec'] = $this->couponSpec;

        return $json;
    }
}
