<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Interface OrderTaxDetailsItemInterface
 */
class TaxDataOrderTaxDetailsItemInterface implements JsonSerializable
{
    /**
     * Type (shipping, product, weee, gift wrapping, etc)
     * @var string|null $type public property
     */
    public $type;

    /**
     * Item id if this item is a product
     * @maps item_id
     * @var integer|null $itemId public property
     */
    public $itemId;

    /**
     * Associated item id if this item is associated with another item, null otherwise
     * @maps associated_item_id
     * @var integer|null $associatedItemId public property
     */
    public $associatedItemId;

    /**
     * Applied taxes
     * @maps applied_taxes
     * @var \MagentoCommunityLib\Models\TaxDataOrderTaxDetailsAppliedTaxInterface[]|null $appliedTaxes public property
     */
    public $appliedTaxes;

    /**
     * ExtensionInterface class for @see \Magento\Tax\Api\Data\OrderTaxDetailsItemInterface
     * @maps extension_attributes
     * @var object|null $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $type                Initialization value for $this->type
     * @param integer $itemId              Initialization value for $this->itemId
     * @param integer $associatedItemId    Initialization value for $this->associatedItemId
     * @param array   $appliedTaxes        Initialization value for $this->appliedTaxes
     * @param object  $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->type                = func_get_arg(0);
            $this->itemId              = func_get_arg(1);
            $this->associatedItemId    = func_get_arg(2);
            $this->appliedTaxes        = func_get_arg(3);
            $this->extensionAttributes = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']                 = $this->type;
        $json['item_id']              = $this->itemId;
        $json['associated_item_id']   = $this->associatedItemId;
        $json['applied_taxes']        = $this->appliedTaxes;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
