<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *Interface GrandTotalRatesInterface
 */
class TaxDataGrandTotalRatesInterface implements JsonSerializable
{
    /**
     * Tax percentage value
     * @required
     * @var string $percent public property
     */
    public $percent;

    /**
     * Rate title
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $percent Initialization value for $this->percent
     * @param string $title   Initialization value for $this->title
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->percent = func_get_arg(0);
            $this->title   = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['percent'] = $this->percent;
        $json['title']   = $this->title;

        return $json;
    }
}
