<?php
/*
 * MagentoCommunityLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MagentoCommunityLib\Models;

use JsonSerializable;

/**
 *List of all weee attributes, their amounts, etc.., that product has
 */
class WeeeDataProductRenderWeeeAdjustmentAttributeInterface implements JsonSerializable
{
    /**
     * Weee attribute amount
     * @required
     * @var string $amount public property
     */
    public $amount;

    /**
     * Tax which is calculated to fixed product tax attribute
     * @required
     * @maps tax_amount
     * @var string $taxAmount public property
     */
    public $taxAmount;

    /**
     * Tax amount of weee attribute
     * @required
     * @maps tax_amount_incl_tax
     * @var string $taxAmountInclTax public property
     */
    public $taxAmountInclTax;

    /**
     * Product amount exclude tax
     * @required
     * @maps amount_excl_tax
     * @var string $amountExclTax public property
     */
    public $amountExclTax;

    /**
     * Weee attribute code
     * @required
     * @maps attribute_code
     * @var string $attributeCode public property
     */
    public $attributeCode;

    /**
     * ExtensionInterface class for @see
     * \Magento\Weee\Api\Data\ProductRender\WeeeAdjustmentAttributeInterface
     * @required
     * @maps extension_attributes
     * @var object $extensionAttributes public property
     */
    public $extensionAttributes;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $amount              Initialization value for $this->amount
     * @param string $taxAmount           Initialization value for $this->taxAmount
     * @param string $taxAmountInclTax    Initialization value for $this->taxAmountInclTax
     * @param string $amountExclTax       Initialization value for $this->amountExclTax
     * @param string $attributeCode       Initialization value for $this->attributeCode
     * @param object $extensionAttributes Initialization value for $this->extensionAttributes
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->amount              = func_get_arg(0);
            $this->taxAmount           = func_get_arg(1);
            $this->taxAmountInclTax    = func_get_arg(2);
            $this->amountExclTax       = func_get_arg(3);
            $this->attributeCode       = func_get_arg(4);
            $this->extensionAttributes = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['amount']               = $this->amount;
        $json['tax_amount']           = $this->taxAmount;
        $json['tax_amount_incl_tax']  = $this->taxAmountInclTax;
        $json['amount_excl_tax']      = $this->amountExclTax;
        $json['attribute_code']       = $this->attributeCode;
        $json['extension_attributes'] = $this->extensionAttributes;

        return $json;
    }
}
